In [92]:
import pandas as pd

In [93]:
wta = pd.read_csv (r"C:\Users\NaiaJon\Documents\Naia\BootcampDataScience\Datos ML\wta.csv", low_memory= False)

In [94]:
# Me hago una copia por si aca
wta_copia = pd.read_csv (r"C:\Users\NaiaJon\Documents\Naia\BootcampDataScience\Datos ML\wta.csv", low_memory= False)

In [95]:
wta.head()

,Tournament,Date,Court,Surface,Round,Best of,Player_1,Player_2,Winner,Rank_1,Rank_2,Pts_1,Pts_2,Odd_1,Odd_2,Score
0,ASB Classic,2007-01-01 00:00:00,Outdoor,Hard,1st Round,3,Sun T.T.,Baker L.,Sun T.T.,81,272,332,90,1.33,3,6-1 6-1
1,ASB Classic,2007-01-01 00:00:00,Outdoor,Hard,1st Round,3,Myskina A.,Dulko G.,Dulko G.,16,59,1000,401,1.22,3.75,1-6 7-6 2-6
2,ASB Classic,2007-01-01 00:00:00,Outdoor,Hard,1st Round,3,Loit E.,Birnerova E.,Loit E.,56,84,418,324,1.72,2,6-1 6-1
3,ASB Classic,2007-01-01 00:00:00,Outdoor,Hard,1st Round,3,Nakamura A.,Craybas J.,Craybas J.,57,70,405,365,1.83,1.83,5-7 2-6
4,ASB Classic,2007-01-01 00:00:00,Outdoor,Hard,1st Round,3,Bartoli M.,Morita A.,Bartoli M.,18,180,951,152,1.16,4.5,7-6 6-3

In [96]:
wta.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44353 entries, 0 to 44352
Data columns (total 16 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Tournament  44353 non-null  object
 1   Date        44353 non-null  object
 2   Court       44353 non-null  object
 3   Surface     44353 non-null  object
 4   Round       44353 non-null  object
 5   Best of     44353 non-null  int64
 6   Player_1    44353 non-null  object
 7   Player_2    44353 non-null  object
 8   Winner      44353 non-null  object
 9   Rank_1      44353 non-null  int64
 10  Rank_2      44353 non-null  int64
 11  Pts_1       44353 non-null  int64
 12  Pts_2       44353 non-null  int64
 13  Odd_1       44353 non-null  object
 14  Odd_2       44353 non-null  object
 15  Score       44353 non-null  object
dtypes: int64(5), object(11)
memory usage: 5.4+ MB

In [97]:
stats_2024= pd.read_csv(r"C:\Users\NaiaJon\Documents\Naia\BootcampDataScience\Datos ML\wta_matches_2024.csv")

In [98]:
stats_2024.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2689 entries, 0 to 2688
Data columns (total 49 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   tourney_id          2689 non-null   object
 1   tourney_name        2689 non-null   object
 2   surface             2632 non-null   object
 3   draw_size           2689 non-null   int64
 4   tourney_level       2689 non-null   object
 5   tourney_date        2689 non-null   int64
 6   match_num           2689 non-null   int64
 7   winner_id           2689 non-null   int64
 8   winner_seed         1132 non-null   float64
 9   winner_entry        454 non-null    object
 10  winner_name         2689 non-null   object
 11  winner_hand         2689 non-null   object
 12  winner_ht           2001 non-null   float64
 13  winner_ioc          2689 non-null   object
 14  winner_age          2689 non-null   float64
 15  loser_id            2689 non-null   int64
 16  loser_seed          682 non-null    float64
 17  loser_entry         727 non-null    object
 18  loser_name          2689 non-null   object
 19  loser_hand          2689 non-null   object
 20  loser_ht            1886 non-null   float64
 21  loser_ioc           2689 non-null   object
 22  loser_age           2687 non-null   float64
 23  score               2689 non-null   object
 24  best_of             2689 non-null   int64
 25  round               2689 non-null   object
 26  minutes             2396 non-null   float64
 27  w_ace               2624 non-null   float64
 28  w_df                2624 non-null   float64
 29  w_svpt              2624 non-null   float64
 30  w_1stIn             2624 non-null   float64
 31  w_1stWon            2624 non-null   float64
 32  w_2ndWon            2624 non-null   float64
 33  w_SvGms             2624 non-null   float64
 34  w_bpSaved           2624 non-null   float64
 35  w_bpFaced           2624 non-null   float64
 36  l_ace               2624 non-null   float64
 37  l_df                2624 non-null   float64
 38  l_svpt              2624 non-null   float64
 39  l_1stIn             2624 non-null   float64
 40  l_1stWon            2624 non-null   float64
 41  l_2ndWon            2624 non-null   float64
 42  l_SvGms             2624 non-null   float64
 43  l_bpSaved           2624 non-null   float64
 44  l_bpFaced           2624 non-null   float64
 45  winner_rank         2686 non-null   float64
 46  winner_rank_points  2686 non-null   float64
 47  loser_rank          2674 non-null   float64
 48  loser_rank_points   2674 non-null   float64
dtypes: float64(29), int64(6), object(14)
memory usage: 1.0+ MB

In [99]:
stats_2024.head()

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,...,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points
0,2024-9900,United Cup,Hard,18,I,20240101,299,216347,NaN,NaN,...,27.0,13.0,7.0,7.0,4.0,8.0,1.0,9505.0,NaN,NaN
1,2024-9900,United Cup,Hard,18,I,20240101,297,216347,NaN,NaN,...,47.0,28.0,7.0,12.0,3.0,8.0,1.0,9505.0,20.0,2330.0
2,2024-9900,United Cup,Hard,18,I,20240101,295,201493,NaN,NaN,...,82.0,47.0,10.0,15.0,11.0,19.0,NaN,NaN,292.0,246.0
3,2024-9900,United Cup,Hard,18,I,20240101,293,216347,NaN,NaN,...,27.0,18.0,6.0,8.0,6.0,11.0,1.0,9505.0,14.0,2770.0
4,2024-9900,United Cup,Hard,18,I,20240101,291,201614,NaN,NaN,...,72.0,51.0,22.0,16.0,3.0,6.0,20.0,2330.0,544.0,89.0

In [100]:
wta.head()

,Tournament,Date,Court,Surface,Round,Best of,Player_1,Player_2,Winner,Rank_1,Rank_2,Pts_1,Pts_2,Odd_1,Odd_2,Score
0,ASB Classic,2007-01-01 00:00:00,Outdoor,Hard,1st Round,3,Sun T.T.,Baker L.,Sun T.T.,81,272,332,90,1.33,3,6-1 6-1
1,ASB Classic,2007-01-01 00:00:00,Outdoor,Hard,1st Round,3,Myskina A.,Dulko G.,Dulko G.,16,59,1000,401,1.22,3.75,1-6 7-6 2-6
2,ASB Classic,2007-01-01 00:00:00,Outdoor,Hard,1st Round,3,Loit E.,Birnerova E.,Loit E.,56,84,418,324,1.72,2,6-1 6-1
3,ASB Classic,2007-01-01 00:00:00,Outdoor,Hard,1st Round,3,Nakamura A.,Craybas J.,Craybas J.,57,70,405,365,1.83,1.83,5-7 2-6
4,ASB Classic,2007-01-01 00:00:00,Outdoor,Hard,1st Round,3,Bartoli M.,Morita A.,Bartoli M.,18,180,951,152,1.16,4.5,7-6 6-3

In [101]:
from ydata_profiling import ProfileReport
profile = ProfileReport(wta, title="Profiling Report")
profile.to_file("wta_report.html")

100%|██████████| 16/16 [00:00<00:00, 45.43it/s]0<00:00, 28.08it/s, Describe variable: Score]
Summarize dataset: 100%|██████████| 41/41 [00:02<00:00, 20.07it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:03<00:00,  3.30s/it]
Render HTML: 100%|██████████| 1/1 [00:00<00:00,  7.06it/s]
Export report to file: 100%|██████████| 1/1 [00:00<00:00, 103.67it/s]

Primer análisis de WTA:  
Tournaments: 238 - creo que da más valor la categoría del torneo GS, Masters1000, Masters500 etc.. ver si lo puedo clasificar  
Court: Outdoor / Indoor ---> muy desbalanceado. Me vale más la superficie. QUitar  
Superficie: dejar en tres: dura, hierba y tierra. Reasignar carpet y greenset que tienen muy pocos registros. Son pistas rápidas. A Hard.
Best of. En femenino es siempre al mejor de tres sets. Fuera.

In [102]:
wta.columns

Index(['Tournament', 'Date', 'Court', 'Surface', 'Round', 'Best of',
       'Player_1', 'Player_2', 'Winner', 'Rank_1', 'Rank_2', 'Pts_1', 'Pts_2',
       'Odd_1', 'Odd_2', 'Score'],
      dtype='object')

In [103]:
wta = wta.drop (columns=['Court','Best of'])

In [104]:
wta['Surface'] = wta['Surface'].replace({'Greenset': 'Hard', 'Carpet': 'Hard'})

In [105]:
wta['Tournament'].unique()

array(['ASB Classic', "Mondial Australian Women's Hardcourts",
       'Moorilla Hobart International', 'Medibank International',
       'Australian Open', 'Toray Pan Pacific Open', 'Open Gaz de France',
       "Pattaya Women's Open", 'Proximus Diamond Games',
       'Sony Ericsson International', 'Copa Colsanitas Santander',
       "Dubai Duty Free Women's Open",
       'Regions Morgan Keegan Championships & the Cellular South Cup',
       'Abierto Mexicano', 'Qatar Total Open', 'Pacific Life Open',
       'Sony Ericsson Open', 'Bausch & Lomb Championships',
       'Family Circle Cup', 'Gaz de France Budapest Grand Prix',
       'Estoril Open', 'J&S Cup', 'Qatar Telecom German Open',
       'ECM Prague Open',
       'FesGrand Prix de SAR La Princesse Lalla Meryem',
       "Internazionali BNL d'Italia", 'Istanbul Cup',
       'Internationaux de Strasbourg', 'French Open', 'Barcelona KIA',
       'DFS Classic', "International Women's Open", 'Ordina Open',
       'Wimbledon', "Western & Southern Financial Group Women's Open",
       'Internazionali Femminili di Tennis di Palermo', 'Gastein Ladies',
       'Bank of the West Classic', 'Acura Classic',
       'Nordea Nordic Light Open', 'East West Bank Classic', 'Toronto',
       'Forest Hills Sony Ericsson WTA Tour Classic ', 'Pilot Pen Tennis',
       'US Open', 'Commonwealth Bank Tennis Classic', 'China Open',
       'Sunfeast Open', 'Banka Koper Slovenia Open',
       "Guangzhou International Women's Open",
       'FORTIS Championships Luxembourg', 'Hansol Korea Open',
       'Porsche Tennis Grand Prix', 'Tashkent Open',
       'AIG Japan Open Tennis Championships', 'PTT Bangkok Open',
       'Kremlin Cup', 'Zurich Open', 'Generali Ladies Linz',
       'Bell Challenge', 'Sony Ericsson Championships', 'Cachantun Cup',
       'Barclays Dubai Tennis Championships',
       'Canara Bank Bangalore Open',
       'Grand Prix de SAR La Princesse Lalla Meryem', 'Rogers Cup',
       'Forest Hills Tennis Classic',
       "TOE Life Ceramics Guangzhou International Women's Open",
       'Brisbane International', 'Copa Sony Ericsson Colsanitas',
       'Monterrey Open', 'BNP Paribas Open',
       'Andalucia Tennis Experience', 'MPS Group Championships',
       'Barcelona Ladies Open', 'Mutua Madrileña Madrid Open',
       'Warsaw Open', 'AEGON Classic ', 'AEGON International',
       'Collector Swedish Open', 'LA Womens Tennis Championships',
       'GDD-Guangzhou International Womens Open ', 'HP Open',
       'Commonwealth Bank Tournament of Champions',
       'Copa BBVA Colsanitas', 'Malaysia Open', 'Unicef Open',
       'e-Boks Sony Ericsson Open', 'Mercury Insurance Open',
       "Landsky Lighting Guangzhou International Women's Open",
       'Dubai Duty Free Tennis Championships', 'Cellular South Cup',
       'Qatar Ladies Open', 'Brussels Open',
       'POLI-FARBE Budapest Grand Prix', 'Baku Cup', 'Citi Open',
       'Texas Tennis Open', 'New Haven Open at Yale',
       "WANLIMA Guangzhou International Women's Open",
       'BGL BNP Paribas Luxembourg Open', 'Apai International',
       'Memphis International', 'Budapest Grand Prix',
       'Mutua Madrid Open', 'Italiacom Open', 'Sony Swedish Open',
       "GRC Bank Guangzhou International Women's Open", 'KDB Korea Open',
       'Qatar Airways Tournament of Champions Sofia',
       'Shenzhen Longgang Gemdale Open', 'Open GDF Suez',
       'Copa Claro Colsanitas', 'US National Indoor Tennis Championships',
       'Brasil Tennis Cup', 'BNP Paribas Katowice Open', 'Portugal Open',
       'Nürnberger Versicherungscup', 'Topshelf Open',
       'Hungarian Grand Prix', 'Southern California Open',
       'Guangzhou Open', 'Garanti Koza WTA Tournament of Champions',
       'Shenzhen Open', 'Hobart International', 'Rio Open',
       'Bucharest Open', 'TEB BNP Paribas Istanbul Cup',
       'Connecticut Open', 'Prudential Hong Kong Tennis Open',
       'Coupe Banque Nationale', 'Kia Korea Open', 'Wuhan Open',
       "Japan Women's Open Tennis", 'Tianjin Open',
       'BNP Paribas Fortis Diamond Games', 'Katowice Open',
       'Grand Prix SAR Lalla Meryem', 'J&T Banka Prague Open',
       'Aegon Open', "Japan Women's Tennis Open", 'WTA Elite Trophy',
       'Ladies Trophy', 'Taiwan Open', 'Mallorca Open',
       'Ladies Championship Gstaad', 'Ericsson Open',
       "Jiangxi Women's Tennis Open", 'Korea Open',
       'BNP Paribas WTA Finals', 'Hungarian Ladies Open',
       'Ladies Open Biel Bienne', 'Ricoh Open', 'Sydney International',
       'Samsung Open', 'Eastbourne International', 'Moscow River Cup',
       'Mubadala Silicon Valley Classic', 'Thailand Open',
       'Rosmalen Grass Court Championships', 'Nottingham Open',
       'Birmingham Classic ', 'Ladies Open Lausanne', 'Baltic Open',
       'Internazionali Femminili di Palermo', 'Bronx Open',
       'Zhengzhou Open', 'Toray Pan Pacific Open Tennis Tournament',
       'WTA Finals', 'Adelaide International', 'Lyon Open',
       'Top Seed Open', 'Ostrava Open',
       "Abu Dhabi WTA Women's Tennis Open", 'Grampians Trophy',
       'Gippsland Trophy', 'Yarra Valley Classic',
       'Phillip Island Trophy', 'Abierto Zapopan', 'Miami Open',
       'Copa Colsanitas', 'Volvo Car Open', "MUSC Health Women's Open",
       'Serbia Ladies Open', 'Emilia-Romagna Open', 'Bett1Open',
       'Viking Classic ', 'Bad Homburg Open', 'Viking International',
       'European Open', 'Budapest Open', 'Prague Open', 'Poland Open',
       'Canadian Open', "Chicago Women's Opeen", 'Tennis in the Land',
       'Luxembourg Open', 'Slovenia Open', 'Chicago Fall Tennis Classic',
       'Astana Open', 'Tenerife Ladies Open', 'Transylvania Open',
       'Courmayeur Ladies Open', 'Generali Ladies Linz Open',
       'Adelaide International 1', 'Melbourne Summer Set 1',
       'Melbourne Summer Set 2', 'Sydney Tennis Classic', 'Qatar Open',
       'Charleston Open', 'Rothesay Classic ', 'Championnats de Granby',
       'Chennai Open', 'Parma Ladies Open', 'Tallinn Open', 'Jasmin Open',
       'San Diego Open', 'Guadalajara Open', 'Adelaide International 2',
       'Ladies Linz Open', 'Merida Open', 'ATX Open', 'Morocco Open',
       'German Open', 'Japan Open', 'Ningbo Open',
       'Hong Kong Tennis Open', 'Jiangxi Tennis Open', 'Open de Rouen',
       'Rothesay International', 'Iasi Open', 'Thailand Open 2',
       'Jiangxi Open', 'Singapore Open', "Queen's Club Championships",
       'Eastbourne Open', 'Hamburg Open', 'SP Open'], dtype=object)

In [106]:
# los nombres vienen con patrocinadores. clasificarlos con las palabras clave
# si alguna (any) de estas palabras (x) está contenida (in) en el nombre del torneo (n)

def clasificar_torneo(nombre):
    n = nombre.lower()
    
    # Grand Slams — nombres estables
    if any(x in n for x in ['australian open', 'roland garros', 'french open', 
                              'wimbledon', 'us open']):
        return 'GS'
    
    # WTA Finals — varios nombres históricos
    if any(x in n for x in ['wta finals', 'wta elite trophy', 'championships',
                              'tournament of champions', 'riyadh finals', 'wta tour championships']):
        return 'WTA_Finals'
  
      # WTA 1000 — los torneos grandes de siempre, por ciudad
    if any(x in n for x in ['indian wells', 'miami', 'madrid', 'roma', 'rome',
                              'internazionali', 'canada', 'toronto', 'rogers',
                              'canadian', 'cincinnati', 'beijing', 'china open',
                              'wuhan', 'doha', 'qatar', 'dubai', 'bnp paribas open',
                              'national bank open', 'sony ericsson open', 
                              'western & southern financial group','shenzhen']):
        return 'WTA1000'
    
    # WTA 500 
    if any(x in n for x in ['abu dhabi','abu dabi', 'adelaide', 'berlin', 'bett1open', 'eastbourne',
                              'Rothesay', 'bad homburg', 'san jose', 'silicon valley',
                              'guangzhou', 'osaka', 'tokyo','toray pan pacific','seoul',
                              'strasbourg', 'birmingham', 'nottingham', 'brisbane',
                              'linz', 'merida', 'monterrey', 'seoul', 'charleston',
                              'stuttgart', 'porsche','washington','mubadala', 'guadalajara',
                              'gdl open akron','family circle cup', 'aegon', 'kremlin',
                              'pilot pen', 'new haven', 'bank of the west',
                              'eastbourne', 'rothesay','birmingham', 'sydney international', 'stanford',
                              'shenzhen', 'luxembourg', 'belgium', 'diamond games', 'fortis', 'san diego',
                              'zhengzhou', 'german']):
        return 'WTA500'
    
    return 'WTA250_o_menor'

wta['tournament_type'] = wta['Tournament'].map(clasificar_torneo)

In [107]:
wta ['tournament_type'].value_counts()

tournament_type
WTA250_o_menor    14363
WTA1000           10261
GS                 9455
WTA500             8343
WTA_Finals         1931
Name: count, dtype: int64

In [108]:
# Cuantos quedan en 250 o menor
sin_clasificar = wta[wta['tournament_type']=='WTA250_o_menor']['Tournament'].nunique()
print(f'Torneos únicos sin clasificar: {sin_clasificar}')
wta[wta['tournament_type']=='WTA250_o_menor']['Tournament'].unique()

Torneos únicos sin clasificar: 145

array(['ASB Classic', "Mondial Australian Women's Hardcourts",
       'Moorilla Hobart International', 'Medibank International',
       'Open Gaz de France', "Pattaya Women's Open",
       'Sony Ericsson International', 'Copa Colsanitas Santander',
       'Abierto Mexicano', 'Pacific Life Open',
       'Gaz de France Budapest Grand Prix', 'Estoril Open', 'J&S Cup',
       'ECM Prague Open',
       'FesGrand Prix de SAR La Princesse Lalla Meryem', 'Istanbul Cup',
       'Barcelona KIA', 'DFS Classic', "International Women's Open",
       'Ordina Open', 'Gastein Ladies', 'Acura Classic',
       'Nordea Nordic Light Open', 'East West Bank Classic',
       'Forest Hills Sony Ericsson WTA Tour Classic ',
       'Commonwealth Bank Tennis Classic', 'Sunfeast Open',
       'Banka Koper Slovenia Open', 'Hansol Korea Open', 'Tashkent Open',
       'PTT Bangkok Open', 'Zurich Open', 'Bell Challenge',
       'Cachantun Cup', 'Canara Bank Bangalore Open',
       'Grand Prix de SAR La Princesse Lalla Meryem',
       'Forest Hills Tennis Classic', 'Copa Sony Ericsson Colsanitas',
       'Andalucia Tennis Experience', 'Barcelona Ladies Open',
       'Warsaw Open', 'Collector Swedish Open', 'HP Open',
       'Copa BBVA Colsanitas', 'Malaysia Open', 'Unicef Open',
       'Mercury Insurance Open', 'Cellular South Cup', 'Brussels Open',
       'POLI-FARBE Budapest Grand Prix', 'Baku Cup', 'Citi Open',
       'Texas Tennis Open', 'Apai International', 'Memphis International',
       'Budapest Grand Prix', 'Italiacom Open', 'Sony Swedish Open',
       'KDB Korea Open', 'Open GDF Suez', 'Copa Claro Colsanitas',
       'Brasil Tennis Cup', 'BNP Paribas Katowice Open', 'Portugal Open',
       'Nürnberger Versicherungscup', 'Topshelf Open',
       'Hungarian Grand Prix', 'Southern California Open',
       'Hobart International', 'Rio Open', 'Bucharest Open',
       'TEB BNP Paribas Istanbul Cup', 'Connecticut Open',
       'Prudential Hong Kong Tennis Open', 'Coupe Banque Nationale',
       'Kia Korea Open', "Japan Women's Open Tennis", 'Tianjin Open',
       'Katowice Open', 'Grand Prix SAR Lalla Meryem',
       'J&T Banka Prague Open', "Japan Women's Tennis Open",
       'Ladies Trophy', 'Taiwan Open', 'Mallorca Open',
       'Ladies Championship Gstaad', 'Ericsson Open',
       "Jiangxi Women's Tennis Open", 'Korea Open',
       'Hungarian Ladies Open', 'Ladies Open Biel Bienne', 'Ricoh Open',
       'Samsung Open', 'Moscow River Cup', 'Thailand Open',
       'Ladies Open Lausanne', 'Baltic Open', 'Bronx Open', 'Lyon Open',
       'Top Seed Open', 'Ostrava Open', 'Grampians Trophy',
       'Gippsland Trophy', 'Yarra Valley Classic',
       'Phillip Island Trophy', 'Abierto Zapopan', 'Copa Colsanitas',
       'Volvo Car Open', "MUSC Health Women's Open", 'Serbia Ladies Open',
       'Viking Classic ', 'Viking International', 'European Open',
       'Budapest Open', 'Prague Open', 'Poland Open',
       "Chicago Women's Opeen", 'Tennis in the Land', 'Slovenia Open',
       'Chicago Fall Tennis Classic', 'Astana Open',
       'Tenerife Ladies Open', 'Transylvania Open',
       'Courmayeur Ladies Open', 'Melbourne Summer Set 1',
       'Melbourne Summer Set 2', 'Sydney Tennis Classic',
       'Championnats de Granby', 'Chennai Open', 'Parma Ladies Open',
       'Tallinn Open', 'Jasmin Open', 'ATX Open', 'Morocco Open',
       'Japan Open', 'Ningbo Open', 'Hong Kong Tennis Open',
       'Jiangxi Tennis Open', 'Open de Rouen', 'Iasi Open',
       'Thailand Open 2', 'Jiangxi Open', 'Singapore Open',
       'Hamburg Open', 'SP Open'], dtype=object)

In [109]:
wta.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44353 entries, 0 to 44352
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Tournament       44353 non-null  object
 1   Date             44353 non-null  object
 2   Surface          44353 non-null  object
 3   Round            44353 non-null  object
 4   Player_1         44353 non-null  object
 5   Player_2         44353 non-null  object
 6   Winner           44353 non-null  object
 7   Rank_1           44353 non-null  int64
 8   Rank_2           44353 non-null  int64
 9   Pts_1            44353 non-null  int64
 10  Pts_2            44353 non-null  int64
 11  Odd_1            44353 non-null  object
 12  Odd_2            44353 non-null  object
 13  Score            44353 non-null  object
 14  tournament_type  44353 non-null  object
dtypes: int64(4), object(11)
memory usage: 5.1+ MB

In [110]:
wta.sample()

,Tournament,Date,Surface,Round,Player_1,Player_2,Winner,Rank_1,Rank_2,Pts_1,Pts_2,Odd_1,Odd_2,Score,tournament_type
31946,Yarra Valley Classic,2021-02-03 00:00:00,Hard,3rd Round,Collins D.,Pliskova Ka.,Collins D.,46,6,1475,5205,2.5,1.53,7-6 7-6,WTA250_o_menor

In [111]:
wta = wta.drop (columns= 'Tournament')
wta['Date'] = pd.to_datetime(wta['Date'], errors='coerce')
wta ['Odd_1'] = pd.to_numeric (wta ['Odd_1'], errors='coerce')
wta ['Odd_2'] = pd.to_numeric (wta ['Odd_2'], errors = 'coerce')

In [112]:
print(wta['Date'].isna().sum())
print(wta['Odd_1'].isna().sum())
print(wta['Odd_2'].isna().sum())

2
1
1

In [113]:
# Ojo, en el futuro voy a dejar los nulos en odds. Pero ahora quiero comprobar sin tener que ejecutar otra vez
# el feature engineering
wta = wta.dropna(subset=['Date', 'Odd_1', 'Odd_2'])

In [81]:
wta.info()

<class 'pandas.core.frame.DataFrame'>
Index: 44349 entries, 0 to 44352
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Date             44349 non-null  datetime64[ns]
 1   Surface          44349 non-null  object
 2   Round            44349 non-null  object
 3   Player_1         44349 non-null  object
 4   Player_2         44349 non-null  object
 5   Winner           44349 non-null  object
 6   Rank_1           44349 non-null  int64
 7   Rank_2           44349 non-null  int64
 8   Pts_1            44349 non-null  int64
 9   Pts_2            44349 non-null  int64
 10  Odd_1            44349 non-null  float64
 11  Odd_2            44349 non-null  float64
 12  Score            44349 non-null  object
 13  tournament_type  44349 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(4), object(7)
memory usage: 5.1+ MB

In [114]:
# Hay valores negativos (será el equivalente a que no había datos)

# Reemplazar -1 por NaN
wta.loc[wta['Odd_1'] < 1, 'Odd_1'] = None
wta.loc[wta['Odd_2'] < 1, 'Odd_2'] = None
#Convertir la cuota de las apuestas a porcentaje: 1/cuota. 1/1.33 = 0.75 (75%)
wta ['prob_1'] = 1/wta ['Odd_1']
wta ['prob_2'] = 1/wta ['Odd_2']
# Cuidado. La suma de apuestas no es igual a 1. Es por la cuota de las casas de apuestas. Lo voy a regularizar
# para que sea la medida refleje la "creencia" real del mercado sobre las posibilidades
wta['total_p'] = wta['prob_1'] + wta['prob_2']

# Normalizar para que sumen 1
wta['prob_1'] = wta['prob_1'] / wta['total_p']
wta['prob_2'] = wta['prob_2'] / wta['total_p']

In [115]:
wta ['Surface'] = wta ['Surface'].astype(str)
wta ['Round'] = wta ['Round'].astype(str)
wta ['Score'] = wta ['Score'].astype(str)
wta ['Player_1'] = wta ['Player_1'].astype(str)
wta ['Player_2'] = wta ['Player_2'].astype(str)
wta ['Winner'] = wta ['Winner'].astype(str)

In [116]:
def winner(fila):
    if fila['Winner'] == fila ["Player_1"]:
        return 1
    else:
        return 2

wta['target'] = wta.apply(winner, axis=1)

In [ ]:
# Comprobaciones
# odd_1 = pd.to_numeric(wta['Odd_1'], errors='coerce')
# odd_2 = pd.to_numeric(wta['Odd_2'], errors='coerce')

# # Ver los valores raros
# print('Odds_1 menores que 1:')
# print(odd_1[odd_1 < 1].value_counts().head(10))

# print('\nOdds_1 negativas:')
# print(odd_1[odd_1 < 0].value_counts().head(10))

# print('\nOdds_1 nulas o cero:')
# print(odd_1[odd_1 == 0].count())

Odds_1 menores que 1:
Odd_1
-1.0    111
Name: count, dtype: int64

Odds_1 negativas:
Odd_1
-1.0    111
Name: count, dtype: int64

Odds_1 nulas o cero:
0

In [54]:
wta.sample (10)

,Date,Surface,Round,Player_1,Player_2,Winner,Rank_1,Rank_2,Pts_1,Pts_2,Odd_1,Odd_2,Score,tournament_type,total_p,prob_1,prob_2,target
24562,2017-05-07,Clay,1st Round,Kuznetsova S.,Shvedova Y.,Kuznetsova S.,9,50,4060,1104,0.892857,0.166667,6-4 6-3,WTA1000,1.059524,0.842697,0.157303,1
14682,2013-03-20,Hard,1st Round,Hampton J.,Niculescu M.,Hampton J.,68,52,898,1130,0.500000,0.581395,6-4 6-3,WTA1000,1.081395,0.462366,0.537634,1
11741,2011-11-05,Hard,Semifinals,Petrova N.,Ivanovic A.,Ivanovic A.,31,26,1645,1945,0.381679,0.666667,1-6 5-7,WTA_Finals,1.048346,0.364078,0.635922,2
16570,2014-01-14,Hard,1st Round,Nara K.,Peng S.,Nara K.,74,43,832,1249,0.400000,0.666667,7-5 4-6 6-3,GS,1.066667,0.375000,0.625000,1
33846,2021-09-30,Hard,Quarterfinals,Cristian J.,Krunic A.,Cristian J.,126,166,607,440,0.500000,0.555556,6-4 6-3,WTA250_o_menor,1.055556,0.473684,0.526316,1
13820,2012-09-27,Hard,Quarterfinals,Radwanska A.,Wozniacki C.,Radwanska A.,3,11,8295,3595,0.555556,0.526316,6-4 6-3,WTA500,1.081871,0.513514,0.486486,1
39593,2024-04-24,Clay,1st Round,Townsend T.,Andreeva M.,Andreeva M.,58,43,1093,1317,0.400000,0.653595,6-4 1-6 5-7,WTA1000,1.053595,0.379653,0.620347,2
21637,2016-02-24,Hard,3rd Round,Bouchard E.,Zheng S.,Zheng S.,61,73,942,820,0.653595,0.421941,6-7 1-6,WTA1000,1.075536,0.607692,0.392308,2
1453,2007-06-29,Grass,3rd Round,Chakvetadze A.,Krajicek M.,Krajicek M.,7,45,2193,538,0.862069,0.222222,6-7 7-6 2-6,GS,1.084291,0.795053,0.204947,2
4819,2009-01-19,Hard,1st Round,O'Brien K.,Niculescu M.,Niculescu M.,160,51,386,1166,0.285714,0.781250,4-6 4-6,GS,1.066964,0.267782,0.732218,2

# Feature engineering
Voy a construir las nuevas features en base a los datos de partidos que tengo:
stado de forma:
% partidos ganados en los últimos 2 meses
% sets ganados en el último 2 meses
Tendencia ranking: si viene 

Histórico:
Head to head histórico
Win rate de cada jugadora en esa superficie concreta
Win rate en esa ronda concreta (hay jugadoras que rinden mejor en finales)
Experiencia de jugadoras (no tengo edad, meto el número de partidos jugados)

In [55]:
wta.head()

,Date,Surface,Round,Player_1,Player_2,Winner,Rank_1,Rank_2,Pts_1,Pts_2,Odd_1,Odd_2,Score,tournament_type,total_p,prob_1,prob_2,target
0,2007-01-01,Hard,1st Round,Sun T.T.,Baker L.,Sun T.T.,81,272,332,90,0.751880,0.333333,6-1 6-1,WTA250_o_menor,1.085213,0.692841,0.307159,1
1,2007-01-01,Hard,1st Round,Myskina A.,Dulko G.,Dulko G.,16,59,1000,401,0.819672,0.266667,1-6 7-6 2-6,WTA250_o_menor,1.086339,0.754527,0.245473,2
2,2007-01-01,Hard,1st Round,Loit E.,Birnerova E.,Loit E.,56,84,418,324,0.581395,0.500000,6-1 6-1,WTA250_o_menor,1.081395,0.537634,0.462366,1
3,2007-01-01,Hard,1st Round,Nakamura A.,Craybas J.,Craybas J.,57,70,405,365,0.546448,0.546448,5-7 2-6,WTA250_o_menor,1.092896,0.500000,0.500000,2
4,2007-01-01,Hard,1st Round,Bartoli M.,Morita A.,Bartoli M.,18,180,951,152,0.862069,0.222222,7-6 6-3,WTA250_o_menor,1.084291,0.795053,0.204947,1

In [56]:
wta.info()

<class 'pandas.core.frame.DataFrame'>
Index: 44349 entries, 0 to 44352
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Date             44349 non-null  datetime64[ns]
 1   Surface          44349 non-null  object
 2   Round            44349 non-null  object
 3   Player_1         44349 non-null  object
 4   Player_2         44349 non-null  object
 5   Winner           44349 non-null  object
 6   Rank_1           44349 non-null  int64
 7   Rank_2           44349 non-null  int64
 8   Pts_1            44349 non-null  int64
 9   Pts_2            44349 non-null  int64
 10  Odd_1            44349 non-null  float64
 11  Odd_2            44349 non-null  float64
 12  Score            44349 non-null  object
 13  tournament_type  44349 non-null  object
 14  total_p          44349 non-null  float64
 15  prob_1           44349 non-null  float64
 16  prob_2           44349 non-null  float64
 17  target           44349 non-null  int64
dtypes: datetime64[ns](1), float64(5), int64(5), object(7)
memory usage: 6.4+ MB

In [117]:
print(wta['prob_1'].describe())
print(wta['prob_2'].describe())

count    44235.000000
mean         0.498412
std          0.214062
min          0.023856
25%          0.337349
50%          0.500000
75%          0.662651
max          0.980769
Name: prob_1, dtype: float64
count    44235.000000
mean         0.501588
std          0.214062
min          0.019231
25%          0.337349
50%          0.500000
75%          0.662651
max          0.976144
Name: prob_2, dtype: float64

In [119]:
wta.head()

,Date,Surface,Round,Player_1,Player_2,Winner,Rank_1,Rank_2,Pts_1,Pts_2,Odd_1,Odd_2,Score,tournament_type,prob_1,prob_2,total_p,target
0,2007-01-01,Hard,1st Round,Sun T.T.,Baker L.,Sun T.T.,81,272,332,90,1.33,3.00,6-1 6-1,WTA250_o_menor,0.692841,0.307159,1.085213,1
1,2007-01-01,Hard,1st Round,Myskina A.,Dulko G.,Dulko G.,16,59,1000,401,1.22,3.75,1-6 7-6 2-6,WTA250_o_menor,0.754527,0.245473,1.086339,2
2,2007-01-01,Hard,1st Round,Loit E.,Birnerova E.,Loit E.,56,84,418,324,1.72,2.00,6-1 6-1,WTA250_o_menor,0.537634,0.462366,1.081395,1
3,2007-01-01,Hard,1st Round,Nakamura A.,Craybas J.,Craybas J.,57,70,405,365,1.83,1.83,5-7 2-6,WTA250_o_menor,0.500000,0.500000,1.092896,2
4,2007-01-01,Hard,1st Round,Bartoli M.,Morita A.,Bartoli M.,18,180,951,152,1.16,4.50,7-6 6-3,WTA250_o_menor,0.795053,0.204947,1.084291,1

In [118]:
wta.to_csv ('wta_copia_mod.csv', index= False)

In [120]:
wta_copia=pd.read_csv ('wta_copia_mod.csv')

In [121]:
wta_copia.head()

,Date,Surface,Round,Player_1,Player_2,Winner,Rank_1,Rank_2,Pts_1,Pts_2,Odd_1,Odd_2,Score,tournament_type,prob_1,prob_2,total_p,target
0,2007-01-01,Hard,1st Round,Sun T.T.,Baker L.,Sun T.T.,81,272,332,90,1.33,3.00,6-1 6-1,WTA250_o_menor,0.692841,0.307159,1.085213,1
1,2007-01-01,Hard,1st Round,Myskina A.,Dulko G.,Dulko G.,16,59,1000,401,1.22,3.75,1-6 7-6 2-6,WTA250_o_menor,0.754527,0.245473,1.086339,2
2,2007-01-01,Hard,1st Round,Loit E.,Birnerova E.,Loit E.,56,84,418,324,1.72,2.00,6-1 6-1,WTA250_o_menor,0.537634,0.462366,1.081395,1
3,2007-01-01,Hard,1st Round,Nakamura A.,Craybas J.,Craybas J.,57,70,405,365,1.83,1.83,5-7 2-6,WTA250_o_menor,0.500000,0.500000,1.092896,2
4,2007-01-01,Hard,1st Round,Bartoli M.,Morita A.,Bartoli M.,18,180,951,152,1.16,4.50,7-6 6-3,WTA250_o_menor,0.795053,0.204947,1.084291,1

In [16]:
def forma_reciente(df, jugadora, fecha_limite, meses=2):

    """Calcula win rate de una jugadora en los dos meses anteriores"""
    
    fecha_inicio = fecha_limite - pd.DateOffset(months=meses)
    
    # partidos donde jugó (como Player_1 o Player_2) en el tiempo indicado (2 meses antes)
    mask = (
        ((df['Player_1'] == jugadora) | (df['Player_2'] == jugadora)) &
        (df['Date'] < fecha_limite) &   
        (df['Date'] >= fecha_inicio)
    )
     
    partidos = df[mask]
    if len(partidos) == 0:
        return 0  # viene de lesión o de mucho tiempo sin competir
    
    victorias = (partidos['Winner'] == jugadora).sum()
    return victorias/len(partidos)

In [17]:
def winrate (df, jugadora, fecha_limite, superficie=None, ronda= None):

    """Calcula win rate de una jugadora en una superficie o en una ronda"""
    
    # partidos donde ha jugado (como Player_1 o Player_2) históricamente
    mask = (
        ((df['Player_1'] == jugadora) | (df['Player_2'] == jugadora)) &
        (df['Date'] < fecha_limite) 
    )
    if superficie:
        mask &= (df['Surface'] == superficie)
    
    if ronda:
        mask &= (df['Round'] == ronda)

    partidos = df[mask]
    if len(partidos) == 0:
        # Tratamiento de nulos. Se entiende que no ha jugado nunca en esa superficie o esa ronda
        # # Valor "novata en esta condición" es algo peor que el 0.5 que sería lo neutro 
        return 0.4  
    
    # Cuantos ha ganado
    victorias = (partidos['Winner'] == jugadora).sum()
    return victorias/len(partidos)

In [18]:
def headtohead (df, p1, p2, fecha_limite):

    """Calcula win rate en el head to head entre las dos jugadoras.
        Devuelve el porcentaje de victorias de la jugadora 1"""

# partidos donde se han enfrentado ANTES de la fecha límite
    mask = (
        (
            ((df['Player_1'] == p1) & (df['Player_2'] == p2)) | 
            ((df['Player_1'] == p2) & (df['Player_2'] == p1))
        ) & (df['Date'] < fecha_limite)
    )
     
    partidos = df[mask]
    if len(partidos) == 0:
        # si no se han enfrentado nunca relleno con lo neutro
        return 0.5  
    
# Aquí contamos cuántas veces ganó P1 específicamente
    victorias_p1 = (partidos['Winner'] == p1).sum()
    return victorias_p1/len(partidos)

In [19]:
def experiencia (df, jugadora, fecha_limite):

    """Calcula el número total de partidos jugados por la jugadora"""

    mask = (
        ((df['Player_1'] == jugadora) | (df['Player_2'] == jugadora)) &
        (df['Date'] < fecha_limite) 
    )

    partidos = df[mask]
    return len(partidos)

In [ ]:
#muestra = wta.sample(5).copy()

In [ ]:
# Voy a crear un nuevo dataframe con las features que será el que entre al modelo

wta = wta.reset_index()

features = []
for i, partido in wta.iterrows():

    
    p1 = partido['Player_1']  
    p2 = partido['Player_2']  
    fecha = partido['Date']
    row = {
        
        # Id para luego poder hacer tracking por si acaso
        'match_id': i,
        'date': partido['Date'],
        'odds_1': partido['prob_1'],
        'odds_2': partido['prob_1'],

        #Features del partido
        'surface': partido['Surface'],
        'round': partido['Round'],

        #Features calculadas para las jugadoras
        'rank_diff': float(partido['Rank_1']) - float(partido['Rank_2']),
        'wins2meses_p1': forma_reciente(wta, p1, fecha),
        'wins2meses_p2': forma_reciente(wta, p2, fecha),
        'ratio_superficie_p1': winrate (wta, p1, fecha, superficie = partido['Surface']),
        'ratio_superficie_p2':winrate (wta, p2, fecha, superficie = partido['Surface']),
        'h2h': headtohead (wta, p1, p2, fecha),
        'ratio_ronda_p1': winrate (wta, p1, fecha, ronda = partido['Round']),
        'ratio_ronda_p2': winrate (wta, p2, fecha, ronda = partido['Round']),
        'experiencia_p1': experiencia (wta, p1, fecha),
        'experiencia_p2': experiencia (wta, p2, fecha),
        #'ratio_total_p1': winrate (wta, p1, fecha, meses=) si lo meto cambiar en app.py
        
        # Target
        'target': partido['target']  # 1 o 2
        }
    features.append(row)
    
#añadir feature de inexperiencia para dar más info a los ceros en forma. ¿es una jugadora novata?

historico_partidos = pd.DataFrame(features)
historico_partidos['is_new_p1'] = (historico_partidos['experiencia_p1'] < 10).astype(int)
historico_partidos['is_new_p2'] = (historico_partidos['experiencia_p2'] < 10).astype(int)
# Guardo el dataframe como archivo para poder recuperarlo sin tener que ejecutarlo todo
historico_partidos.to_csv ('historico_partidos.csv', index=False) 
# Para leerlo pd.read_csv ('historico_partidos.csv', parse_dates=['date']), si no pierde el formato de fecha

In [ ]:
# Hay nulos en algunas features:
#  wins2meses --> Si no hay partidos en los dos meses anteriores (lesiones): rellenar con cero
# ratio_ronda o ratio_superficie --> puede no haber jugado nunca esa ronda. Poner un cero penaliza, no es tanto
# que sea horrible en esa superficie como que es neutro, mejor rellenar con 0.5
# Además 2007 estará muy incompleto puesto que es la fecha de inicio. No voy a tenerlo en cuenta en el entrenamiento

In [209]:
historico_partidos.columns

Index(['match_id', 'surface', 'round', 'rank_diff', 'wins2meses_p1',
       'wins2meses_p2', 'ratio_superficie_p1', 'ratio_superficie_p2', 'h2h',
       'ratio_ronda_p1', 'ratio_ronda_p2', 'experiencia_p1', 'experiencia_p2',
       'target', 'Date'],
      dtype='object')

In [135]:
len(historico_partidos [historico_partidos['Date'].dt.year == 2007])

2391

In [247]:
historico_partidos = historico_partidos [historico_partidos['date'].dt.year != 2007]

In [248]:
historico_partidos.info()

<class 'pandas.core.frame.DataFrame'>
Index: 41958 entries, 29 to 44348
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   match_id             41958 non-null  int64
 1   date                 41958 non-null  datetime64[ns]
 2   surface              41958 non-null  object
 3   round                41958 non-null  object
 4   rank_diff            41958 non-null  float64
 5   wins2meses_p1        41958 non-null  float64
 6   wins2meses_p2        41958 non-null  float64
 7   ratio_superficie_p1  41958 non-null  float64
 8   ratio_superficie_p2  41958 non-null  float64
 9   h2h                  41958 non-null  float64
 10  ratio_ronda_p1       41958 non-null  float64
 11  ratio_ronda_p2       41958 non-null  float64
 12  experiencia_p1       41958 non-null  int64
 13  experiencia_p2       41958 non-null  int64
 14  target               41958 non-null  int64
dtypes: datetime64[ns](1), float64(8), int64(4), object(2)
memory usage: 5.1+ MB

In [249]:
profile = ProfileReport(historico_partidos, title="Profiling Report")
profile.to_file("historico_report.html")

c:\Users\NaiaJon\AppData\Local\Programs\Python\Python311\Lib\site-packages\ydata_profiling\utils\dataframe.py:137: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={"index": "df_index"}, inplace=True)
100%|██████████| 15/15 [00:00<00:00, 117.11it/s]<00:00, 57.93it/s, Describe variable: target]
Summarize dataset: 100%|██████████| 145/145 [00:15<00:00,  9.47it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:04<00:00,  4.41s/it]
Render HTML: 100%|██████████| 1/1 [00:00<00:00,  1.68it/s]
Export report to file: 100%|██████████| 1/1 [00:00<00:00, 38.81it/s]

In [ ]:
jugadora = 'Sabalenka A.'
fecha_limite = pd.to_datetime('2025-12-17')
num = experiencia (wta, jugadora, fecha_limite)
h2h= headtohead (wta, jugadora, 'Badosa P.', fecha_limite)
wins = winrate (wta, jugadora, fecha_limite, superficie='Clay')
forma = forma_reciente(wta, jugadora, fecha_limite, meses=2)

In [244]:
print (f"Experiencia: {num} partidos, H2h: {h2h}, rate tierra: {wins}, forma: {forma}")

Experiencia: 514 partidos, H2h: 0.7142857142857143, rate tierra: 0.7368421052631579, forma: 1.0

In [5]:
historico_partidos = pd.read_csv ('historico_partidos.csv', parse_dates=['date'])

In [ ]:
# Me lo había cargado en algún ir y venir. Cuidado con el flujo final!
# historico_partidos['tournament_type'] = historico_partidos['match_id'].map(
#     wta.set_index(wta.index)['Tournament'].map(clasificar_torneo))

In [15]:
historico_partidos.to_csv ('historico_partidos.csv', index=False)