# GridSearch & Pipelines
GridSearch es una herramienta de optimización que usamos cuando ajustamos hiperparámetros. Definimos la cuadrícula(grid) de parámetros que queremos buscar y seleccionamos la mejor combinación de parámetros para nuestros datos.

## Método 1
Itera un único algoritmo sobre un conjunto de hiperparámetros, mediante la validación cruzada, iterando con el dataset dividido en train y val para recoger los errores y evaluar la mejor métrica.

In [1]:
# Ignora los deprecation warnings
import warnings

warnings.filterwarnings("ignore", category=DeprecationWarning)

In [2]:
from sklearn import svm, datasets
from sklearn.model_selection import GridSearchCV
iris = datasets.load_iris()

# Lista de parámetros a probar
parameters = {
    'kernel': ['linear', 'rbf', 'sigmoid', 'poly'],
    'C': [0.001, 0.1, 0.5, 1, 5, 10, 100],
    'degree': [1,2,3,4,5,6,7],
    'gamma': ['scale', 'auto']
}

svc = svm.SVC()
# n_jobs: usa todos los cores del ordenador. Si por ejemplo quiero poder usar el pc pa otra cosa aquí indicaría los hilos que quiero 
# q use
# Este PC tiene 8 procesadores lógicos. en n_jobs le diría cuantos de esos tiene que usar
clf = GridSearchCV(estimator = svc,
                  param_grid = parameters,
                  n_jobs = -1, 
                  cv = 10, 
                  scoring="accuracy")

clf.fit(iris.data, iris.target)

GridSearchCV(cv=10, estimator=SVC(), n_jobs=-1,
             param_grid={'C': [0.001, 0.1, 0.5, 1, 5, 10, 100],
                         'degree': [1, 2, 3, 4, 5, 6, 7],
                         'gamma': ['scale', 'auto'],
                         'kernel': ['linear', 'rbf', 'sigmoid', 'poly']},
             scoring='accuracy')

In [ ]:
clf.best_estimator_
#modelo sólo era svc. Los parámetros salen ahí también

SVC(C=0.1, degree=2, gamma='auto', kernel='poly')

In [ ]:
print(clf.best_params_) # salen arriba pero también puedo sacarlos así
print(clf.best_score_)

{'C': 0.1, 'degree': 2, 'gamma': 'auto', 'kernel': 'poly'}
0.9866666666666667

In [5]:
from sklearn.model_selection import cross_val_score
clf = svm.SVC(C=0.1, degree=2, gamma='auto', kernel='poly')
scores = cross_val_score(clf, iris.data, iris.target, cv=10)
scores

array([1.        , 0.93333333, 1.        , 1.        , 1.        ,
       1.        , 0.93333333, 1.        , 1.        , 1.        ])

In [6]:
import numpy as np
print(np.mean(scores))
print(np.std(scores))

0.9866666666666667
0.026666666666666658

## Método 2

Una forma más senior es montar un único gridsearch para iterar con varios modelos con otros hiperparámetros y con la validación cruzada.

In [7]:
import pickle

In [8]:
# Load libraries
import numpy as np
from sklearn import datasets
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.model_selection import train_test_split 
from sklearn import svm
# Set random seed
np.random.seed(0)

In [9]:
# Load data
iris = datasets.load_iris()
X = iris.data
y = iris.target

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X,
                                                    y,
                                                    test_size=0.2,
                                                    random_state=2)

In [ ]:
# para crearlo tengo que indicarle algo al crear el pipe. No significa que sólo vaya a probar esos

pipe = Pipeline(steps=[("scaler", StandardScaler()),
    ('classifier', RandomForestClassifier())
])
#En steps puedo meter todos los pasos que sean de sklearn (onehotencoding podríamos hacerlo aquí tb)

logistic_params = {
    'classifier': [LogisticRegression(max_iter=1000, solver='liblinear'), LogisticRegression(max_iter=10, solver='liblinear')],
    'classifier__penalty': ['l1', 'l2'] #aplicar ridge y lasso
}

random_forest_params = {
    'scaler': [StandardScaler(), MinMaxScaler()],
    'classifier': [RandomForestClassifier()],
    'classifier__max_depth': [2,3]
}

svm_param = {
    'classifier': [svm.SVC()], # kernel rbf (gaussiano)
    'classifier__C': [0.001, 0.1, 0.5, 1, 5, 10, 100],
}

# Aquí meto todo
search_space = [
    logistic_params,
    random_forest_params,
    svm_param
]

clf = GridSearchCV(estimator = pipe,
                  param_grid = search_space,
                  cv = 5,
                  n_jobs=-1)

clf.fit(X_train, y_train)

c:\Users\NaiaJon\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\model_selection\_validation.py:490: FitFailedWarning:
20 fits failed out of a total of 75.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
20 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\NaiaJon\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\model_selection\_validation.py", line 833, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\NaiaJon\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py", line 1336, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\NaiaJon\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\pipeline.py", line 621, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "c:\Users\NaiaJon\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py", line 1336, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\NaiaJon\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1208, in fit
    raise ValueError(
ValueError: The 'liblinear' solver does not support multiclass classification (n_classes >= 3). Either use another solver or wrap the estimator in a OneVsRestClassifier to keep applying a one-versus-rest scheme.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
c:\Users\NaiaJon\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\model_selection\_search.py:1137: UserWarning: One or more of the test scores are non-finite: [       nan        nan        nan        nan 0.96666667 0.95833333
 0.95833333 0.96666667 0.38333333 0.9        0.95833333 0.95833333
 0.94166667 0.95       0.925     ]
  warnings.warn(

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('scaler', StandardScaler()),
                                       ('classifier',
                                        RandomForestClassifier())]),
             n_jobs=-1,
             param_grid=[{'classifier': [LogisticRegression(max_iter=1000,
                                                            solver='liblinear'),
                                         LogisticRegression(max_iter=10,
                                                            solver='liblinear')],
                          'classifier__penalty': ['l1', 'l2']},
                         {'classifier': [RandomForestClassifier()],
                          'classifier__max_depth': [2, 3],
                          'scaler': [StandardScaler(), MinMaxScaler()]},
                         {'classifier': [SVC()],
                          'classifier__C': [0.001, 0.1, 0.5, 1, 5, 10, 100]}])

In [12]:
print(clf.best_estimator_)
print(clf.best_score_)
print(clf.best_params_)

Pipeline(steps=[('scaler', StandardScaler()),
                ('classifier', RandomForestClassifier(max_depth=2))])
0.9666666666666668
{'classifier': RandomForestClassifier(), 'classifier__max_depth': 2, 'scaler': StandardScaler()}

In [ ]:
# Le metemos el X_test sin escalar porque él ya internamente tiene el escalado (además lo ha creado con su fit y transform solo con
# la parte buena)
clf.best_estimator_.predict(X_test)

array([0, 0, 2, 0, 0, 2, 0, 2, 2, 0, 0, 0, 0, 0, 1, 1, 0, 1, 2, 1, 2, 1,
       2, 1, 1, 0, 0, 2, 0, 2])

In [14]:
clf.best_estimator_.score(X_test,y_test)

0.9666666666666667

## Método 3

Otro uso puede ser la construcción de pipelines (tuberías) específicos para cada tipo de modelo.

In [15]:
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV
from sklearn.feature_selection import SelectKBest # basado en p-values
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score

import pandas as pd
import numpy as np

from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

In [16]:
reg_log = Pipeline(steps = [
    ("imputer", SimpleImputer()), # llena missings con estadísticos sencillos (media, mediana...)
    ("scaler", StandardScaler()),
    ("reglog", LogisticRegression())
])
reg_log_param = {
    "imputer__strategy": ['mean', 'median'],    
#    "reglog__penalty": ['l1', 'l2'],
    "reglog__penalty": ['l2'], 
    "reglog__C": np.logspace(0, 4, 10) # para C pruebame 10 valores entre 10^0 y 10^4
}

In [ ]:
rand_forest = RandomForestClassifier()
rand_forest_param = {
    "n_estimators": [50, 100, 150],
    "max_features": [1,2,3]
}


svm = Pipeline(steps=[
    ("scaler", StandardScaler()),
    ("selectkbest", SelectKBest()),
    ("svm", SVC())
])


svm_param = {
    # estrategia de selección de features entre 2,3,4. Pero las selecciona en base a estadísticos
    'selectkbest__k': [2, 3, 4], 
    'svm__kernel': ['linear', 'rbf', 'sigmoid', 'poly'],
    'svm__C': [0.001, 0.1, 0.5, 1, 5, 10, 100],
    'svm__degree': [1,2,3,4],
    'svm__gamma': ['scale', 'auto']
}

# Aquí me prueba todas las opciones definidas para el logistic regressor. Rellena los nulos, etc...
# Estamos metiendo un Pipe dentro del grid
gs_reg_log = GridSearchCV(reg_log,
                         reg_log_param,
                         cv = 10,
                         scoring = 'accuracy',
                         verbose = 1,
                         n_jobs = -1)

gs_rand_forest = GridSearchCV(rand_forest,
                         rand_forest_param,
                         cv = 10,
                         scoring = 'accuracy',
                         verbose = 1,
                         n_jobs = -1)

gs_svm = GridSearchCV(svm,
                         svm_param,
                         cv = 10,
                         scoring = 'accuracy',
                         verbose = 1,
                         n_jobs = -1)

# Me hago un diccionario con los tres grids
grids = {"gs_reg_log": gs_reg_log,
        "gs_rand_forest": gs_rand_forest,
        "gs_svm": gs_svm}

In [18]:
from sklearn.model_selection import train_test_split 
X = iris.data
y = iris.target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
# Recorro los grids y los voy entrenando
for nombre, grid_search in grids.items():
    grid_search.fit(X_train, y_train)

Fitting 10 folds for each of 20 candidates, totalling 200 fits

c:\Users\NaiaJon\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(

Fitting 10 folds for each of 9 candidates, totalling 90 fits
Fitting 10 folds for each of 672 candidates, totalling 6720 fits

Acaba de probar más de 680 modelos entrenados más de 8000 veces
Podría probarse dentro del grid distintos modelos también. La diferencia es que te va a dar el mejor modelo y sus parámentros pero no vas a ver qué ha pasado con el resto.
Aquí estamos viendo por separado los tres, sus mejores parámetros y además cuando de lejos están unos de otros. A veces pueden estar cerca y ser mejor quedarte con uno más sencillo

In [20]:
print(gs_reg_log.best_score_)
print(gs_reg_log.best_params_)
print(gs_reg_log.best_estimator_)
print(gs_reg_log.best_estimator_['reglog'])

0.9583333333333334
{'imputer__strategy': 'mean', 'reglog__C': np.float64(7.742636826811269), 'reglog__penalty': 'l2'}
Pipeline(steps=[('imputer', SimpleImputer()), ('scaler', StandardScaler()),
                ('reglog',
                 LogisticRegression(C=np.float64(7.742636826811269),
                                    penalty='l2'))])
LogisticRegression(C=np.float64(7.742636826811269), penalty='l2')

In [21]:
print(gs_rand_forest.best_score_)
print(gs_rand_forest.best_params_)
print(gs_rand_forest.best_estimator_)

0.9333333333333332
{'max_features': 1, 'n_estimators': 100}
RandomForestClassifier(max_features=1)

In [22]:
print(gs_svm.best_score_)
print(gs_svm.best_params_)
print(gs_svm.best_estimator_)
print(gs_svm.best_estimator_['svm'])

0.9666666666666668
{'selectkbest__k': 4, 'svm__C': 5, 'svm__degree': 1, 'svm__gamma': 'scale', 'svm__kernel': 'linear'}
Pipeline(steps=[('scaler', StandardScaler()), ('selectkbest', SelectKBest(k=4)),
                ('svm', SVC(C=5, degree=1, kernel='linear'))])
SVC(C=5, degree=1, kernel='linear')

In [ ]:
best_grids = [(i, j.best_score_) for i, j in grids.items()]

best_grids = pd.DataFrame(best_grids, columns=["Grid", "Best score"]).sort_values(by="Best score", ascending=False)
best_grids
# Tienen resultados similares svm y regresión logística. Igual me quedaba con reg_log

             Grid  Best score
2          gs_svm    0.966667
0      gs_reg_log    0.958333
1  gs_rand_forest    0.933333

In [25]:
gs_svm.best_estimator_

Pipeline(steps=[('scaler', StandardScaler()), ('selectkbest', SelectKBest(k=4)),
                ('svm', SVC(C=5, degree=1, kernel='linear'))])

In [26]:
preds = gs_svm.best_estimator_.predict(X_test)
accuracy_score(y_test, preds)

0.9666666666666667

In [27]:
gs_reg_log.best_estimator_

Pipeline(steps=[('imputer', SimpleImputer()), ('scaler', StandardScaler()),
                ('reglog',
                 LogisticRegression(C=np.float64(7.742636826811269),
                                    penalty='l2'))])

In [28]:
preds = gs_reg_log.best_estimator_.predict(X_test)
accuracy_score(y_test, preds)

1.0

In [29]:
preds = gs_rand_forest.best_estimator_.predict(X_test)
accuracy_score(y_test, preds)

1.0

 Tanto la regresión logística (pipeline) como el random forest son los modelos que mejor generalizan

In [30]:
gs_svm.best_estimator_

Pipeline(steps=[('scaler', StandardScaler()), ('selectkbest', SelectKBest(k=4)),
                ('svm', SVC(C=5, degree=1, kernel='linear'))])

In [31]:
gs_svm.best_estimator_['svm']

SVC(C=5, degree=1, kernel='linear')

In [32]:
preds = gs_svm.best_estimator_.predict(X_test)
accuracy_score(y_test, preds)

0.9666666666666667

In [33]:
gs_svm.best_estimator_['svm']

SVC(C=5, degree=1, kernel='linear')

In [34]:
# El mejor modelo ha sido
best_model = gs_reg_log.best_estimator_
best_model.score(X_test, y_test)

1.0

In [35]:
gs_reg_log.best_params_

{'imputer__strategy': 'mean',
 'reglog__C': np.float64(7.742636826811269),
 'reglog__penalty': 'l2'}

In [36]:
# El mejor modelo ha sido
best_model = gs_reg_log.best_estimator_
best_model.score(X_test, y_test)

1.0

In [37]:
gs_reg_log.best_estimator_

Pipeline(steps=[('imputer', SimpleImputer()), ('scaler', StandardScaler()),
                ('reglog',
                 LogisticRegression(C=np.float64(7.742636826811269),
                                    penalty='l2'))])

En train cv el reg_log mejor que random forest. Además es el más sencillo.

In [38]:
# El mejor modelo ha sido
best_model = gs_reg_log.best_estimator_
best_model.score(X_test, y_test)

1.0

In [39]:
gs_reg_log.best_estimator_

Pipeline(steps=[('imputer', SimpleImputer()), ('scaler', StandardScaler()),
                ('reglog',
                 LogisticRegression(C=np.float64(7.742636826811269),
                                    penalty='l2'))])

In [40]:
# Puedo guardarme el mejor modelo y recuperarlo en cualquier otro momento sin necesidad de ejecutar todo lo anterior

import pickle

filename = 'finished_model'

with open(filename, 'wb') as archivo_salida:
    pickle.dump(best_model, archivo_salida)

In [41]:
# Aquí lo recuperaría

with open(filename, 'rb') as archivo_entrada:
    modelo_importado = pickle.load(archivo_entrada)

In [ ]:
# Aquí ya tenemos el modelo entrenado
modelo_importado.score(X_test, y_test)*100

100.0

¿Cuando hay que re-entrenar un modelo? En la vida real un modelo tiene que tener un seguimiento para ver cómo van variando las métricas (puede ser que con el tiempo la naturaleza de los datos puede ir cambiando y se puede desajustar).

In [43]:
modelo_importado.predict(X_test)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

In [44]:
modelo_importado

Pipeline(steps=[('imputer', SimpleImputer()), ('scaler', StandardScaler()),
                ('reglog',
                 LogisticRegression(C=np.float64(7.742636826811269),
                                    penalty='l2'))])

In [ ]:
# modelo_importado.predict(X_new)

Ya hemos escogido modelo gracias a los datos de validación. Ahora habría que entrenar el modelo con TODOS los datos de train.

## RandomSearch
El problema que tiene el GridSearchCV es que computacionalmente es muy costoso cuando el espacio dimensional de los hiperparámetros es grande.

Mediante el RandomSearch no se prueban todas las combinaciones, sino unas cuantas de manera aleatoria. Funciona bien con datasets con pocas features. Incluso [hay papers](https://www.jmlr.org/papers/v13/bergstra12a.html) que aseguran que es más eficiente RandomSearch frente a GridSearch

In [45]:
np.logspace(0, 4, 10)

array([1.00000000e+00, 2.78255940e+00, 7.74263683e+00, 2.15443469e+01,
       5.99484250e+01, 1.66810054e+02, 4.64158883e+02, 1.29154967e+03,
       3.59381366e+03, 1.00000000e+04])

In [46]:
# En el mismo tiempo suele dar mejores resultados que el gridsearch. Obviamente el gridsearch va a llegar a este caso
from sklearn.model_selection import RandomizedSearchCV

reg_log = Pipeline(steps=[
                          ("imputer",SimpleImputer()),
                          ("scaler",StandardScaler()),
                          ("reglog",LogisticRegression())
                         ])

reg_log_param = {    
                 "imputer__strategy": ['mean', 'median', 'most_frequent'],
#                 "reglog__penalty": ["l1","l2"], 
                 "reglog__penalty": ["l2"], 
                 "reglog__C": np.logspace(0, 4, 10)
                }


search = RandomizedSearchCV(reg_log,
                           reg_log_param,
                           n_iter = 50,
                           scoring='accuracy',
                           n_jobs=-1,
                           cv=10)

# execute search
result = search.fit(X_train, y_train)

# summarize result
print('Best Score: %s' % result.best_score_)
print('Best Hyperparameters: %s' % result.best_params_)
print('Best Estimator: %s' % result.best_estimator_)

c:\Users\NaiaJon\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\model_selection\_search.py:324: UserWarning: The total space of parameters 30 is smaller than n_iter=50. Running 30 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(

Best Score: 0.9583333333333334
Best Hyperparameters: {'reglog__penalty': 'l2', 'reglog__C': np.float64(7.742636826811269), 'imputer__strategy': 'mean'}
Best Estimator: Pipeline(steps=[('imputer', SimpleImputer()), ('scaler', StandardScaler()),
                ('reglog',
                 LogisticRegression(C=np.float64(7.742636826811269),
                                    penalty='l2'))])

c:\Users\NaiaJon\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(

In [47]:
# summarize result
print('Best Score: %s' % result.best_score_)
print('Best Hyperparameters: %s' % result.best_params_)
print('Best Estimator: %s' % result.best_estimator_)

Best Score: 0.9583333333333334
Best Hyperparameters: {'reglog__penalty': 'l2', 'reglog__C': np.float64(7.742636826811269), 'imputer__strategy': 'mean'}
Best Estimator: Pipeline(steps=[('imputer', SimpleImputer()), ('scaler', StandardScaler()),
                ('reglog',
                 LogisticRegression(C=np.float64(7.742636826811269),
                                    penalty='l2'))])

### Otros Steps

In [48]:
df = pd.read_csv('data/titanic.csv')

In [49]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    str
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    str
 8   class        891 non-null    str
 9   who          891 non-null    str
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    str
 12  embark_town  889 non-null    str
 13  alive        891 non-null    str
 14  alone        891 non-null    bool
dtypes: bool(2), float64(2), int64(4), str(7)
memory usage: 92.4 KB

In [50]:
df = df[['survived', 'age', 'fare', 'class', 'embark_town']]
df.head()

   survived   age     fare  class  embark_town
0         0  22.0   7.2500  Third  Southampton
1         1  38.0  71.2833  First    Cherbourg
2         1  26.0   7.9250  Third  Southampton
3         1  35.0  53.1000  First  Southampton
4         0  35.0   8.0500  Third  Southampton

In [51]:
X = df.drop('survived', axis=1)
y = df['survived']

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

# ColumnTransformer aplica transformaciones. Lo hace con los 'métodos' de sklearn de forma que está automatizado.
# Es más robusto y más fácil para automatizar. Gestiona él solo los 'problemas'. Si salen cosas que no ha visto por ejemplo
column_transformer = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), ['age', 'fare']),
        ('cat', OneHotEncoder(), ['class', 'embark_town'])
    ]
)

X_transformado = column_transformer.fit_transform(X)

In [53]:
X_transformado

array([[-0.53037664, -0.50244517,  0.        , ...,  0.        ,
         1.        ,  0.        ],
       [ 0.57183099,  0.78684529,  1.        , ...,  0.        ,
         0.        ,  0.        ],
       [-0.25482473, -0.48885426,  0.        , ...,  0.        ,
         1.        ,  0.        ],
       ...,
       [        nan, -0.17626324,  0.        , ...,  0.        ,
         1.        ,  0.        ],
       [-0.25482473, -0.04438104,  1.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.15850313, -0.49237783,  0.        , ...,  1.        ,
         0.        ,  0.        ]], shape=(891, 9))

In [54]:
X_new = pd.DataFrame(X_transformado)
X_new.columns = column_transformer.get_feature_names_out()
X_new.head()

,num__age,num__fare,cat__class_First,cat__class_Second,cat__class_Third,cat__embark_town_Cherbourg,cat__embark_town_Queenstown,cat__embark_town_Southampton,cat__embark_town_nan
0,-0.530377,-0.502445,0.0,0.0,1.0,0.0,0.0,1.0,0.0
1,0.571831,0.786845,1.0,0.0,0.0,1.0,0.0,0.0,0.0
2,-0.254825,-0.488854,0.0,0.0,1.0,0.0,0.0,1.0,0.0
3,0.365167,0.420730,1.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0.365167,-0.486337,0.0,0.0,1.0,0.0,0.0,1.0,0.0

In [1]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import FunctionTransformer

preprocessor = ColumnTransformer(
    transformers=[
        ('log', FunctionTransformer(np.log1p), ['columna_a_transformar']),

    ]
)

NameError: name 'np' is not defined

In [56]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [57]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.ensemble import RandomForestClassifier

# Definir preprocesamiento
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), ['age', 'fare']),
        ('cat', OneHotEncoder(), ['class', 'embark_town'])
    ]
)

# Crear el pipeline completo
pipeline = Pipeline(steps=[
    ('preprocessing', preprocessor),
    ('classifier', RandomForestClassifier())
])

# Entrenar el pipeline
pipeline.fit(X_train, y_train)

# Predecir
y_pred = pipeline.predict(X_test)

In [58]:
y_pred

array([0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 1])

# Análisis exploratorio automatizado

In [3]:
import pandas as pd

In [4]:
from sklearn import datasets

In [5]:
iris = datasets.load_iris()

In [6]:
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df['target'] = iris.target
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [63]:
%pip install ydata-profiling setuptools==78.1.1

Collecting ydata-profiling
  Downloading ydata_profiling-4.18.4-py2.py3-none-any.whl.metadata (23 kB)
Collecting setuptools==78.1.1
  Downloading setuptools-78.1.1-py3-none-any.whl.metadata (6.5 kB)
Collecting scipy<1.17,>=1.8 (from ydata-profiling)
  Downloading scipy-1.16.3-cp311-cp311-win_amd64.whl.metadata (60 kB)
     ---------------------------------------- 0.0/60.8 kB ? eta -:--:--
     ---------------------------------------- 60.8/60.8 kB 1.6 MB/s eta 0:00:00
Collecting pandas!=1.4.0,<3.0,>1.5 (from ydata-profiling)
  Downloading pandas-2.3.3-cp311-cp311-win_amd64.whl.metadata (19 kB)
Collecting matplotlib<=3.10,>=3.5 (from ydata-profiling)
  Downloading matplotlib-3.10.0-cp311-cp311-win_amd64.whl.metadata (11 kB)
Collecting pydantic<3,>=2 (from ydata-profiling)
  Downloading pydantic-2.13.3-py3-none-any.whl.metadata (108 kB)
     ---------------------------------------- 0.0/108.8 kB ? eta -:--:--
     -------------------------------------- 108.8/108.8 kB 3.2 MB/s eta 0:00:00
Collecting PyYAML<6.1,>=6.0.3 (from ydata-profiling)
  Downloading pyyaml-6.0.3-cp311-cp311-win_amd64.whl.metadata (2.4 kB)
Requirement already satisfied: jinja2<3.2,>=3.1.6 in c:\users\naiajon\appdata\local\programs\python\python311\lib\site-packages (from ydata-profiling) (3.1.6)
Collecting visions<0.8.2,>=0.7.5 (from visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling)
  Downloading visions-0.8.1-py3-none-any.whl.metadata (11 kB)
Collecting numpy<2.4,>=1.22 (from ydata-profiling)
  Downloading numpy-2.3.5-cp311-cp311-win_amd64.whl.metadata (60 kB)
     ---------------------------------------- 0.0/60.9 kB ? eta -:--:--
     ---------------------------------------- 60.9/60.9 kB ? eta 0:00:00
Collecting minify-html>=0.15.0 (from ydata-profiling)
  Downloading minify_html-0.18.1-cp311-cp311-win_amd64.whl.metadata (18 kB)
Collecting filetype>=1.0.0 (from ydata-profiling)
  Downloading filetype-1.2.0-py2.py3-none-any.whl.metadata (6.5 kB)
Collecting phik<0.13,>=0.12.5 (from ydata-profiling)
  Downloading phik-0.12.5-cp311-cp311-win_amd64.whl.metadata (5.6 kB)
Requirement already satisfied: requests<3,>=2.32.0 in c:\users\naiajon\appdata\local\programs\python\python311\lib\site-packages (from ydata-profiling) (2.32.5)
Collecting tqdm<5,>=4.66.3 (from ydata-profiling)
  Downloading tqdm-4.67.3-py3-none-any.whl.metadata (57 kB)
     ---------------------------------------- 0.0/57.7 kB ? eta -:--:--
     ---------------------------------------- 57.7/57.7 kB 3.0 MB/s eta 0:00:00
Requirement already satisfied: seaborn<0.14,>=0.10.1 in c:\users\naiajon\appdata\local\programs\python\python311\lib\site-packages (from ydata-profiling) (0.13.2)
Collecting multimethod<2,>=1.4 (from ydata-profiling)
  Downloading multimethod-1.12-py3-none-any.whl.metadata (9.6 kB)
Requirement already satisfied: statsmodels<1,>=0.13.2 in c:\users\naiajon\appdata\local\programs\python\python311\lib\site-packages (from ydata-profiling) (0.14.6)
Collecting typeguard<5,>=4 (from ydata-profiling)
  Downloading typeguard-4.5.1-py3-none-any.whl.metadata (3.8 kB)
Collecting imagehash==4.3.2 (from ydata-profiling)
  Downloading ImageHash-4.3.2-py2.py3-none-any.whl.metadata (8.4 kB)
Requirement already satisfied: wordcloud>=1.9.4 in c:\users\naiajon\appdata\local\programs\python\python311\lib\site-packages (from ydata-profiling) (1.9.6)
Collecting dacite<2,>=1.9 (from ydata-profiling)
  Downloading dacite-1.9.2-py3-none-any.whl.metadata (17 kB)
Collecting numba<0.63,>=0.60 (from ydata-profiling)
  Downloading numba-0.62.1-cp311-cp311-win_amd64.whl.metadata (2.9 kB)
Collecting PyWavelets (from imagehash==4.3.2->ydata-profiling)
  Downloading pywavelets-1.9.0-cp311-cp311-win_amd64.whl.metadata (7.6 kB)
Requirement already satisfied: pillow in c:\users\naiajon\appdata\local\programs\python\python311\lib\site-packages (from imagehash==4.3.2->ydata-profiling) (12.1.1)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\naiajon\appdata\local\programs\python\python311\lib\site-packages (from jinja2<3.2,>=3.1.6->ydata-profiling) (3.0.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\naiajon\appdata\local\programs\python\python311\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\naiajon\appdata\local\programs\python\python311\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\naiajon\appdata\local\programs\python\python311\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\naiajon\appdata\local\programs\python\python311\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\naiajon\appdata\roaming\python\python311\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (26.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\naiajon\appdata\local\programs\python\python311\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\naiajon\appdata\roaming\python\python311\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (2.9.0.post0)
Collecting llvmlite<0.46,>=0.45.0dev0 (from numba<0.63,>=0.60->ydata-profiling)
  Downloading llvmlite-0.45.1-cp311-cp311-win_amd64.whl.metadata (5.0 kB)
Collecting pytz>=2020.1 (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling)
  Downloading pytz-2026.1.post1-py2.py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: tzdata>=2022.7 in c:\users\naiajon\appdata\local\programs\python\python311\lib\site-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2025.3)
Requirement already satisfied: joblib>=0.14.1 in c:\users\naiajon\appdata\local\programs\python\python311\lib\site-packages (from phik<0.13,>=0.12.5->ydata-profiling) (1.5.3)
Collecting annotated-types>=0.6.0 (from pydantic<3,>=2->ydata-profiling)
  Downloading annotated_types-0.7.0-py3-none-any.whl.metadata (15 kB)
Collecting pydantic-core==2.46.3 (from pydantic<3,>=2->ydata-profiling)
  Downloading pydantic_core-2.46.3-cp311-cp311-win_amd64.whl.metadata (6.7 kB)
Requirement already satisfied: typing-extensions>=4.14.1 in c:\users\naiajon\appdata\roaming\python\python311\site-packages (from pydantic<3,>=2->ydata-profiling) (4.15.0)
Collecting typing-inspection>=0.4.2 (from pydantic<3,>=2->ydata-profiling)
  Downloading typing_inspection-0.4.2-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\naiajon\appdata\local\programs\python\python311\lib\site-packages (from requests<3,>=2.32.0->ydata-profiling) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in c:\users\naiajon\appdata\local\programs\python\python311\lib\site-packages (from requests<3,>=2.32.0->ydata-profiling) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\naiajon\appdata\local\programs\python\python311\lib\site-packages (from requests<3,>=2.32.0->ydata-profiling) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\naiajon\appdata\local\programs\python\python311\lib\site-packages (from requests<3,>=2.32.0->ydata-profiling) (2026.2.25)
Requirement already satisfied: patsy>=0.5.6 in c:\users\naiajon\appdata\local\programs\python\python311\lib\site-packages (from statsmodels<1,>=0.13.2->ydata-profiling) (1.0.2)
Requirement already satisfied: colorama in c:\users\naiajon\appdata\roaming\python\python311\site-packages (from tqdm<5,>=4.66.3->ydata-profiling) (0.4.6)
Requirement already satisfied: attrs>=19.3.0 in c:\users\naiajon\appdata\local\programs\python\python311\lib\site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (25.4.0)
Collecting networkx>=2.4 (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling)
  Downloading networkx-3.6.1-py3-none-any.whl.metadata (6.8 kB)
Collecting puremagic (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling)
  Downloading puremagic-1.30-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: six>=1.5 in c:\users\naiajon\appdata\roaming\python\python311\site-packages (from python-dateutil>=2.7->matplotlib<=3.10,>=3.5->ydata-profiling) (1.17.0)
Downloading setuptools-78.1.1-py3-none-any.whl (1.3 MB)
   ---------------------------------------- 0.0/1.3 MB ? eta -:--:--
   ------- -------------------------------- 0.2/1.3 MB 7.3 MB/s eta 0:00:01
   ------------------------- -------------- 0.8/1.3 MB 10.1 MB/s eta 0:00:01
   ---------------------------------------- 1.3/1.3 MB 10.0 MB/s eta 0:00:00
Downloading ydata_profiling-4.18.4-py2.py3-none-any.whl (400 kB)
   ---------------------------------------- 0.0/400.8 kB ? eta -:--:--
   --------------------------------------- 400.8/400.8 kB 26.0 MB/s eta 0:00:00
Downloading ImageHash-4.3.2-py2.py3-none-any.whl (296 kB)
   ---------------------------------------- 0.0/296.7 kB ? eta -:--:--
   -------------------------------------- - 286.7/296.7 kB 8.9 MB/s eta 0:00:01
   ---------------------------------------- 296.7/296.7 kB 6.2 MB/s eta 0:00:00
Downloading dacite-1.9.2-py3-none-any.whl (16 kB)
Downloading filetype-1.2.0-py2.py3-none-any.whl (19 kB)
Downloading matplotlib-3.10.0-cp311-cp311-win_amd64.whl (8.0 MB)
   ---------------------------------------- 0.0/8.0 MB ? eta -:--:--
   --- ------------------------------------ 0.8/8.0 MB 24.1 MB/s eta 0:00:01
   -------- ------------------------------- 1.7/8.0 MB 21.4 MB/s eta 0:00:01
   ------------- -------------------------- 2.7/8.0 MB 21.3 MB/s eta 0:00:01
   ------------------ --------------------- 3.8/8.0 MB 21.8 MB/s eta 0:00:01
   ------------------------ --------------- 4.9/8.0 MB 23.9 MB/s eta 0:00:01
   ----------------------------- ---------- 6.0/8.0 MB 22.4 MB/s eta 0:00:01
   ----------------------------------- ---- 7.1/8.0 MB 24.0 MB/s eta 0:00:01
   ---------------------------------------  8.0/8.0 MB 23.3 MB/s eta 0:00:01
   ---------------------------------------- 8.0/8.0 MB 22.3 MB/s eta 0:00:00
Downloading minify_html-0.18.1-cp311-cp311-win_amd64.whl (3.1 MB)
   ---------------------------------------- 0.0/3.1 MB ? eta -:--:--
   ----------------------- ---------------- 1.8/3.1 MB 56.3 MB/s eta 0:00:01
   ---------------------------------------  3.1/3.1 MB 39.3 MB/s eta 0:00:01
   ---------------------------------------- 3.1/3.1 MB 33.1 MB/s eta 0:00:00
Downloading multimethod-1.12-py3-none-any.whl (10 kB)
Downloading numba-0.62.1-cp311-cp311-win_amd64.whl (2.7 MB)
   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--
   ---------------------- ----------------- 1.6/2.7 MB 49.9 MB/s eta 0:00:01
   ------------------------------------ --- 2.5/2.7 MB 40.1 MB/s eta 0:00:01
   ---------------------------------------- 2.7/2.7 MB 25.1 MB/s eta 0:00:00
Downloading numpy-2.3.5-cp311-cp311-win_amd64.whl (13.1 MB)
   ---------------------------------------- 0.0/13.1 MB ? eta -:--:--
   --- ------------------------------------ 1.3/13.1 MB 40.3 MB/s eta 0:00:01
   ------- -------------------------------- 2.6/13.1 MB 33.2 MB/s eta 0:00:01
   ------------ --------------------------- 3.9/13.1 MB 31.5 MB/s eta 0:00:01
   ---------------- ----------------------- 5.3/13.1 MB 30.7 MB/s eta 0:00:01
   ------------------- -------------------- 6.3/13.1 MB 28.9 MB/s eta 0:00:01
   ----------------------- ---------------- 7.7/13.1 MB 28.8 MB/s eta 0:00:01
   --------------------------- ------------ 9.2/13.1 MB 29.2 MB/s eta 0:00:01
   -------------------------------- ------- 10.5/13.1 MB 29.7 MB/s eta 0:00:01
   ------------------------------------ --- 12.1/13.1 MB 29.7 MB/s eta 0:00:01
   ---------------------------------------  13.1/13.1 MB 28.5 MB/s eta 0:00:01
   ---------------------------------------- 13.1/13.1 MB 26.1 MB/s eta 0:00:00
Downloading pandas-2.3.3-cp311-cp311-win_amd64.whl (11.3 MB)
   ---------------------------------------- 0.0/11.3 MB ? eta -:--:--
   ---- ----------------------------------- 1.3/11.3 MB 42.0 MB/s eta 0:00:01
   -------- ------------------------------- 2.4/11.3 MB 31.2 MB/s eta 0:00:01
   -------------- ------------------------- 4.0/11.3 MB 31.9 MB/s eta 0:00:01
   ------------------ --------------------- 5.3/11.3 MB 30.8 MB/s eta 0:00:01
   ----------------------- ---------------- 6.7/11.3 MB 30.7 MB/s eta 0:00:01
   ----------------------------- ---------- 8.2/11.3 MB 30.9 MB/s eta 0:00:01
   --------------------------------- ------ 9.6/11.3 MB 30.7 MB/s eta 0:00:01
   ------------------------------------ --- 10.5/11.3 MB 29.7 MB/s eta 0:00:01
   ------------------------------------ --- 10.5/11.3 MB 29.7 MB/s eta 0:00:01
   ---------------------------------------  11.3/11.3 MB 25.2 MB/s eta 0:00:01
   ---------------------------------------- 11.3/11.3 MB 23.3 MB/s eta 0:00:00
Downloading phik-0.12.5-cp311-cp311-win_amd64.whl (675 kB)
   ---------------------------------------- 0.0/675.0 kB ? eta -:--:--
   --------------------------------------- 675.0/675.0 kB 41.5 MB/s eta 0:00:00
Downloading pydantic-2.13.3-py3-none-any.whl (471 kB)
   ---------------------------------------- 0.0/472.0 kB ? eta -:--:--
   --------------------------------------- 472.0/472.0 kB 30.8 MB/s eta 0:00:00
Downloading pydantic_core-2.46.3-cp311-cp311-win_amd64.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   -------------------------------- ------- 1.7/2.1 MB 53.8 MB/s eta 0:00:01
   ---------------------------------------- 2.1/2.1 MB 33.2 MB/s eta 0:00:00
Downloading pyyaml-6.0.3-cp311-cp311-win_amd64.whl (158 kB)
   ---------------------------------------- 0.0/158.8 kB ? eta -:--:--
   ---------------------------------------- 158.8/158.8 kB 9.3 MB/s eta 0:00:00
Downloading scipy-1.16.3-cp311-cp311-win_amd64.whl (38.7 MB)
   ---------------------------------------- 0.0/38.7 MB ? eta -:--:--
   - -------------------------------------- 1.4/38.7 MB 43.3 MB/s eta 0:00:01
   -- ------------------------------------- 2.9/38.7 MB 37.0 MB/s eta 0:00:01
   ---- ----------------------------------- 4.3/38.7 MB 34.1 MB/s eta 0:00:02
   ----- ---------------------------------- 5.6/38.7 MB 30.0 MB/s eta 0:00:02
   ------- -------------------------------- 7.0/38.7 MB 32.1 MB/s eta 0:00:01
   -------- ------------------------------- 8.5/38.7 MB 32.1 MB/s eta 0:00:01
   --------- ------------------------------ 9.2/38.7 MB 30.9 MB/s eta 0:00:01
   ----------- ---------------------------- 10.8/38.7 MB 29.7 MB/s eta 0:00:01
   ------------ --------------------------- 11.8/38.7 MB 28.5 MB/s eta 0:00:01
   ------------- -------------------------- 12.7/38.7 MB 27.3 MB/s eta 0:00:01
   -------------- ------------------------- 13.9/38.7 MB 26.2 MB/s eta 0:00:01
   --------------- ------------------------ 14.8/38.7 MB 25.1 MB/s eta 0:00:01
   ---------------- ----------------------- 15.8/38.7 MB 24.3 MB/s eta 0:00:01
   ----------------- ---------------------- 16.6/38.7 MB 23.4 MB/s eta 0:00:01
   ----------------- ---------------------- 17.0/38.7 MB 21.8 MB/s eta 0:00:01
   ------------------ --------------------- 18.1/38.7 MB 21.1 MB/s eta 0:00:01
   ------------------- -------------------- 19.1/38.7 MB 20.5 MB/s eta 0:00:01
   -------------------- ------------------- 20.3/38.7 MB 21.1 MB/s eta 0:00:01
   ---------------------- ----------------- 21.6/38.7 MB 21.1 MB/s eta 0:00:01
   ----------------------- ---------------- 23.0/38.7 MB 21.8 MB/s eta 0:00:01
   ------------------------- -------------- 24.3/38.7 MB 22.6 MB/s eta 0:00:01
   -------------------------- ------------- 25.4/38.7 MB 23.4 MB/s eta 0:00:01
   --------------------------- ------------ 26.4/38.7 MB 23.4 MB/s eta 0:00:01
   ---------------------------- ----------- 27.6/38.7 MB 25.2 MB/s eta 0:00:01
   ----------------------------- ---------- 28.7/38.7 MB 25.2 MB/s eta 0:00:01
   ------------------------------ --------- 29.8/38.7 MB 26.2 MB/s eta 0:00:01
   ------------------------------- -------- 30.9/38.7 MB 25.1 MB/s eta 0:00:01
   --------------------------------- ------ 32.0/38.7 MB 24.2 MB/s eta 0:00:01
   ---------------------------------- ----- 33.3/38.7 MB 24.3 MB/s eta 0:00:01
   ----------------------------------- ---- 34.4/38.7 MB 24.2 MB/s eta 0:00:01
   ------------------------------------ --- 35.6/38.7 MB 24.2 MB/s eta 0:00:01
   ------------------------------------- -- 36.6/38.7 MB 24.2 MB/s eta 0:00:01
   -------------------------------------- - 37.5/38.7 MB 23.4 MB/s eta 0:00:01
   ---------------------------------------  38.5/38.7 MB 24.2 MB/s eta 0:00:01
   ---------------------------------------  38.7/38.7 MB 24.2 MB/s eta 0:00:01
   ---------------------------------------- 38.7/38.7 MB 20.4 MB/s eta 0:00:00
Downloading tqdm-4.67.3-py3-none-any.whl (78 kB)
   ---------------------------------------- 0.0/78.4 kB ? eta -:--:--
   ---------------------------------------- 78.4/78.4 kB ? eta 0:00:00
Downloading typeguard-4.5.1-py3-none-any.whl (36 kB)
Downloading visions-0.8.1-py3-none-any.whl (105 kB)
   ---------------------------------------- 0.0/105.4 kB ? eta -:--:--
   ---------------------------------------- 105.4/105.4 kB 6.3 MB/s eta 0:00:00
Downloading annotated_types-0.7.0-py3-none-any.whl (13 kB)
Downloading llvmlite-0.45.1-cp311-cp311-win_amd64.whl (38.1 MB)
   ---------------------------------------- 0.0/38.1 MB ? eta -:--:--
   - -------------------------------------- 1.1/38.1 MB 33.9 MB/s eta 0:00:02
   -- ------------------------------------- 2.7/38.1 MB 34.1 MB/s eta 0:00:02
   --- ------------------------------------ 3.8/38.1 MB 30.3 MB/s eta 0:00:02
   ---- ----------------------------------- 4.2/38.1 MB 29.6 MB/s eta 0:00:02
   ---- ----------------------------------- 4.8/38.1 MB 21.7 MB/s eta 0:00:02
   ------ --------------------------------- 6.1/38.1 MB 22.8 MB/s eta 0:00:02
   ------- -------------------------------- 7.5/38.1 MB 23.8 MB/s eta 0:00:02
   --------- ------------------------------ 8.8/38.1 MB 24.4 MB/s eta 0:00:02
   ---------- ----------------------------- 10.2/38.1 MB 25.1 MB/s eta 0:00:02
   ------------ --------------------------- 11.7/38.1 MB 25.1 MB/s eta 0:00:02
   ------------- -------------------------- 13.3/38.1 MB 25.2 MB/s eta 0:00:01
   --------------- ------------------------ 14.8/38.1 MB 31.2 MB/s eta 0:00:01
   ---------------- ----------------------- 16.1/38.1 MB 31.2 MB/s eta 0:00:01
   ------------------ --------------------- 17.4/38.1 MB 29.7 MB/s eta 0:00:01
   ------------------- -------------------- 18.3/38.1 MB 31.2 MB/s eta 0:00:01
   ------------------- -------------------- 19.0/38.1 MB 28.5 MB/s eta 0:00:01
   --------------------- ------------------ 20.1/38.1 MB 27.3 MB/s eta 0:00:01
   ---------------------- ----------------- 21.3/38.1 MB 27.3 MB/s eta 0:00:01
   ----------------------- ---------------- 22.8/38.1 MB 27.3 MB/s eta 0:00:01
   ------------------------- -------------- 24.6/38.1 MB 27.3 MB/s eta 0:00:01
   --------------------------- ------------ 26.0/38.1 MB 27.3 MB/s eta 0:00:01
   ---------------------------- ----------- 27.4/38.1 MB 27.3 MB/s eta 0:00:01
   ----------------------------- ---------- 28.5/38.1 MB 27.3 MB/s eta 0:00:01
   ------------------------------- -------- 29.7/38.1 MB 29.7 MB/s eta 0:00:01
   -------------------------------- ------- 30.6/38.1 MB 28.5 MB/s eta 0:00:01
   --------------------------------- ------ 31.8/38.1 MB 28.5 MB/s eta 0:00:01
   ---------------------------------- ----- 33.1/38.1 MB 27.3 MB/s eta 0:00:01
   ----------------------------------- ---- 34.2/38.1 MB 26.2 MB/s eta 0:00:01
   ------------------------------------ --- 35.3/38.1 MB 25.1 MB/s eta 0:00:01
   ------------------------------------- -- 36.2/38.1 MB 24.3 MB/s eta 0:00:01
   ---------------------------------------  37.4/38.1 MB 24.2 MB/s eta 0:00:01
   ---------------------------------------  38.1/38.1 MB 25.2 MB/s eta 0:00:01

  WARNING: Failed to remove contents in a temporary directory 'C:\Users\NaiaJon\AppData\Local\Programs\Python\Python311\Lib\site-packages\~umpy.libs'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\NaiaJon\AppData\Local\Programs\Python\Python311\Lib\site-packages\~umpy'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\NaiaJon\AppData\Local\Programs\Python\Python311\Lib\site-packages\~cipy.libs'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\NaiaJon\AppData\Local\Programs\Python\Python311\Lib\site-packages\~cipy'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\NaiaJon\AppData\Local\Programs\Python\Python311\Lib\site-packages\~andas'.
  You can safely remove it manually.

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [1]:
from ydata_profiling import ProfileReport

c:\Users\NaiaJon\AppData\Local\Programs\Python\Python311\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
C:\Users\NaiaJon\AppData\Local\Temp\ipykernel_22652\44057814.py:1: DeprecationWarning:
    `import ydata_profiling` is deprecated and will not receive more updates.
    Please install fg-data-profiling via `pip install fg-data-profiling` and use `import data_profiling` instead.

  from ydata_profiling import ProfileReport

In [ ]:
# Genera un EDA automático 
profile = ProfileReport(df, title="Profiling Report")
profile.to_file("your_report.html")

100%|██████████| 5/5 [00:00<?, ?it/s]/10 [00:00<00:00, 88.75it/s, Describe variable: target]
Summarize dataset: 100%|██████████| 30/30 [00:01<00:00, 26.32it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:00<00:00,  1.28it/s]
Render HTML: 100%|██████████| 1/1 [00:00<00:00,  4.70it/s]
Export report to file: 100%|██████████| 1/1 [00:00<00:00, 288.78it/s]