# Working with datetime in Pandas DataFrame

In [10]:
import pandas as pd
import numpy as np

### 1. Dates and Times in Python
Python's basic objects for working with dates and times reside in the built-in ``datetime`` module.
Along with the third-party ``dateutil`` module, you can use it to quickly perform a host of useful functionalities on dates and times.
For example, you can manually build a date using the ``datetime`` type:

In [1]:
from datetime import datetime
datetime(year = 2015, month = 7, day = 4)

datetime.datetime(2015, 7, 4, 0, 0)

Or, using the ``dateutil`` module, you can parse dates from a variety of string formats:

In [2]:
# https://dateutil.readthedocs.io/en/stable/parser.html#functions
from dateutil import parser
print(parser.parse("4th of July, 2015"))
print(parser.parse("07/04/2015"))
print(parser.parse("07/04/2015", dayfirst=True))

2015-07-04 00:00:00
2015-07-04 00:00:00
2015-04-07 00:00:00

In [ ]:
print(parser.parse("7/4/2015"))
print(parser.parse("07-04-2015"))
print(parser.parse("2015-07-04"))

Once you have a ``datetime`` object, you can do things like printing the day of the week:

In [3]:
# https://docs.python.org/3/library/datetime.html#strftime-and-strptime-behavior
datetime(year = 2015, month = 7, day = 4).strftime('%w')

'6'

### 2. Dates and Times in numpy

In [4]:
import numpy as np
date = np.array('2015-07-04', dtype = np.datetime64)
date

array('2015-07-04', dtype='datetime64[D]')

Once we have this date formatted, however, we can quickly do vectorized operations on it:

In [5]:
date

array('2015-07-04', dtype='datetime64[D]')

In [6]:
# delta es una diferencia. 5 días de diferencia
np.timedelta64(5, 'D')

np.timedelta64(5,'D')

In [ ]:
# se lo puedo sumar. Fecha 5 días más allá
date + np.timedelta64(5, 'D')

np.datetime64('2015-07-09')

In [8]:
dates = date + np.arange(12)
dates

array(['2015-07-04', '2015-07-05', '2015-07-06', '2015-07-07',
       '2015-07-08', '2015-07-09', '2015-07-10', '2015-07-11',
       '2015-07-12', '2015-07-13', '2015-07-14', '2015-07-15'],
      dtype='datetime64[D]')

Here is a minute-based datetime:

In [ ]:
# Puedo usar horas, minutos segundos
np.datetime64('2015-07-04 12:00:30')

The following table, drawn from the [NumPy datetime64 documentation](http://docs.scipy.org/doc/numpy/reference/arrays.datetime.html), lists the available format codes along with the relative and absolute timespans that they can encode:

Numpy permite escalas mucho mayores. Para casos específicos es posible necesitar usarlas

|Code    | Meaning     | Time span (relative) | Time span (absolute)   |
|--------|-------------|----------------------|------------------------|
| ``Y``  | Year	       | ± 9.2e18 years       | [9.2e18 BC, 9.2e18 AD] |
| ``M``  | Month       | ± 7.6e17 years       | [7.6e17 BC, 7.6e17 AD] |
| ``W``  | Week	       | ± 1.7e17 years       | [1.7e17 BC, 1.7e17 AD] |
| ``D``  | Day         | ± 2.5e16 years       | [2.5e16 BC, 2.5e16 AD] |
| ``h``  | Hour        | ± 1.0e15 years       | [1.0e15 BC, 1.0e15 AD] |
| ``m``  | Minute      | ± 1.7e13 years       | [1.7e13 BC, 1.7e13 AD] |
| ``s``  | Second      | ± 2.9e12 years       | [ 2.9e9 BC, 2.9e9 AD]  |
| ``ms`` | Millisecond | ± 2.9e9 years        | [ 2.9e6 BC, 2.9e6 AD]  |
| ``us`` | Microsecond | ± 2.9e6 years        | [290301 BC, 294241 AD] |
| ``ns`` | Nanosecond  | ± 292 years          | [ 1678 AD, 2262 AD]    |
| ``ps`` | Picosecond  | ± 106 days           | [ 1969 AD, 1970 AD]    |
| ``fs`` | Femtosecond | ± 2.6 hours          | [ 1969 AD, 1970 AD]    |
| ``as`` | Attosecond  | ± 9.2 seconds        | [ 1969 AD, 1970 AD]    |

### 3. Dates and Times in Pandas

#### Default arguments

In [11]:
df = pd.DataFrame({'date': ['3/10/2000', '3/11/2000', '3/12/2000'],
                   'value': [2, 3, 4]})
df

        date  value
0  3/10/2000      2
1  3/11/2000      3
2  3/12/2000      4

In [12]:
df.dtypes

date       str
value    int64
dtype: object

In [13]:
df['date'] = pd.to_datetime(df['date'])
df

        date  value
0 2000-03-10      2
1 2000-03-11      3
2 2000-03-12      4

In [14]:
df.dtypes

date     datetime64[us]
value             int64
dtype: object

#### Day first format

In [ ]:
#Hace el parseo indicándole que empieza por día
df = pd.DataFrame({'date': ['3/10/2000', '3/11/2000', '3/12/2000'],
                   'value': [2, 3, 4]})

df['date'] = pd.to_datetime(df['date'], dayfirst=True)
df

        date  value
0 2000-10-03      2
1 2000-11-03      3
2 2000-12-03      4

#### Custom format

In [ ]:
# Le meto el formato a mano si es uno que no reconoce
df = pd.DataFrame({'date': ['2016-6-10 20:30:0', 
                            '2016-7-1 19:45:30', 
                            '2013-10-12 4:5:1'],
                   'value': [2, 3, 4]})

df['date'] = pd.to_datetime(df['date'], format="%Y-%m-%d %H:%M:%S")
df

                 date  value
0 2016-06-10 20:30:00      2
1 2016-07-01 19:45:30      3
2 2013-10-12 04:05:01      4

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    3 non-null      datetime64[us]
 1   value   3 non-null      int64
dtypes: datetime64[us](1), int64(1)
memory usage: 180.0 bytes

In [ ]:
# Es capaz de parsear muchos formatos de fecha de forma correcta
from datetime import datetime
dates = pd.to_datetime([datetime(2015, 7, 3), '4th of July, 2015',
                       '2015-Jul-6', '07-07-2015', '20150708'])
dates

DatetimeIndex(['2015-07-03', '2015-07-04', '2015-07-06', '2015-07-07',
               '2015-07-08'],
              dtype='datetime64[us]', freq=None)

#### Handle parsing error

In [20]:
# Hay errores que ya no parsea
df = pd.DataFrame({'date': ['3/10/2000', 'a/11/2000', '3/12/2000'],
                   'value': [2, 3, 4]})

df['date'] = pd.to_datetime(df['date'])

ValueError: time data "a/11/2000" doesn't match format "%m/%d/%Y". You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [21]:
df = pd.DataFrame({'date': ['3/10/2000', 'a/11/2000', '3/12/2000'],
                   'value': [2, 3, 4]})

df['date'] = pd.to_datetime(df['date'], errors = 'ignore')
df.dtypes

AssertionError:

In [22]:
df['date']

0    3/10/2000
1    a/11/2000
2    3/12/2000
Name: date, dtype: str

In [23]:
df

        date  value
0  3/10/2000      2
1  a/11/2000      3
2  3/12/2000      4

In [ ]:
df = pd.DataFrame({'date': ['3/10/2000', 'a/11/2000', '3/12/2000'],
                   'value': [2, 3, 4]})

df['date'] = pd.to_datetime(df['date'], errors = 'coerce') #traduce los errores a NaT (not a Time) y pierde la información original
df

        date  value
0 2000-03-10      2
1        NaT      3
2 2000-03-12      4

In [25]:
df['date'][df['date'].isna()]

1   NaT
Name: date, dtype: datetime64[us]

In [ ]:
df.dtypes

### 4. Assemble a datetime from multiple columns

In [26]:
df = pd.DataFrame({'year': [2015, 2016],
                   'month': [2, 3],
                   'day': [4, 5]})

df

   year  month  day
0  2015      2    4
1  2016      3    5

In [27]:
df.dtypes

year     int64
month    int64
day      int64
dtype: object

In [28]:
df['date'] = pd.to_datetime(df)

In [29]:
df

   year  month  day       date
0  2015      2    4 2015-02-04
1  2016      3    5 2016-03-05

In [30]:
df.dtypes

year              int64
month             int64
day               int64
date     datetime64[us]
dtype: object

### 5. Get year, month and day

Una vez convertido a datetime hay un montón de funciones que permiten trabajar con la fecha

In [31]:
df = pd.DataFrame({'name': ['Tom', 'Andy', 'Lucas'],
                 'DoB': ['08-05-1997', '04-28-1996', '12-16-1995']})

df['DoB'] = pd.to_datetime(df['DoB'])
df

    name        DoB
0    Tom 1997-08-05
1   Andy 1996-04-28
2  Lucas 1995-12-16

In [32]:
df['year'] = df['DoB'].dt.year
df['month'] = df['DoB'].dt.month
df['day'] = df['DoB'].dt.day
df

    name        DoB  year  month  day
0    Tom 1997-08-05  1997      8    5
1   Andy 1996-04-28  1996      4   28
2  Lucas 1995-12-16  1995     12   16

In [ ]:
df.dtypes

### 6. Get the week of year, the day of week and leap year

In [ ]:
df['week_of_year'] = df['DoB'].dt.isocalendar().week
df['day_of_week'] = df['DoB'].dt.dayofweek
df['is_leap_year'] = df['DoB'].dt.is_leap_year #es bisiesto?
df

    name        DoB  year  month  day  week_of_year  day_of_week  is_leap_year
0    Tom 1997-08-05  1997      8    5            32            1         False
1   Andy 1996-04-28  1996      4   28            17            6          True
2  Lucas 1995-12-16  1995     12   16            50            5         False

In [ ]:
dw_mapping={
    0: 'Monday', 
    1: 'Tuesday', 
    2: 'Wednesday', 
    3: 'Thursday', 
    4: 'Friday',
    5: 'Saturday', 
    6: 'Sunday'
} 
df['day_of_week_name']=df['DoB'].dt.weekday.map(dw_mapping)
df

### 7. Get the age from the date of birth

In [34]:
pd.to_datetime('today')

Timestamp('2026-04-14 13:32:53.080832')

In [35]:
datetime.today()

datetime.datetime(2026, 4, 14, 13, 33, 0, 386095)

In [ ]:
# Calcula edades 
today = pd.to_datetime('today')
df['age'] = today.year - df['DoB'].dt.year

df

,name,DoB,year,month,day,week_of_year,day_of_week,is_leap_year,age
0,Tom,1997-08-05,1997,8,5,32,1,False,29
1,Andy,1996-04-28,1996,4,28,17,6,True,30
2,Lucas,1995-12-16,1995,12,16,50,5,False,31

### 8. Improve performance by setting date column as the index

In [37]:
# Si sé que las fechas van a ser relevantes conviene que ponerlo como índice
df = pd.read_csv('data/city_sales.csv', parse_dates = ['date'])
df.set_index(['date'], inplace=True)
df.head()

                     num    city
date
2015-01-01 09:00:00    4  London
2015-01-01 09:01:00    4  London
2015-01-01 09:02:00    3  London
2015-01-01 09:03:00    3  London
2015-01-01 09:04:00    3  London

In [38]:
# Tenemos un DateTimeIndex
df.index

DatetimeIndex(['2015-01-01 09:00:00', '2015-01-01 09:01:00',
               '2015-01-01 09:02:00', '2015-01-01 09:03:00',
               '2015-01-01 09:04:00', '2015-01-01 09:05:00',
               '2015-01-01 09:06:00', '2015-01-01 09:07:00',
               '2015-01-01 09:08:00', '2015-01-01 09:09:00',
               ...
               '2019-01-31 15:51:00', '2019-01-31 15:52:00',
               '2019-01-31 15:53:00', '2019-01-31 15:54:00',
               '2019-01-31 15:55:00', '2019-01-31 15:56:00',
               '2019-01-31 15:57:00', '2019-01-31 15:58:00',
               '2019-01-31 15:59:00', '2019-01-31 16:00:00'],
              dtype='datetime64[us]', name='date', length=1795144, freq=None)

### 9. Select data with a specific year and perform aggregation

In [ ]:
#Puedo entrar directamente por el año en el índice
df.loc['2018']

                     num       city
date
2018-01-01 09:00:00    2     London
2018-01-01 09:01:00    1     London
2018-01-01 09:02:00    3     London
2018-01-01 09:03:00    3     London
2018-01-01 09:04:00    3     London
...                  ...        ...
2018-12-31 15:56:00    4  Cambridge
2018-12-31 15:57:00    2  Cambridge
2018-12-31 15:58:00    3  Cambridge
2018-12-31 15:59:00    3  Cambridge
2018-12-31 16:00:00    2  Cambridge

[439524 rows x 2 columns]

In [40]:
df.loc['2018', 'num'].head()

date
2018-01-01 09:00:00    2
2018-01-01 09:01:00    1
2018-01-01 09:02:00    3
2018-01-01 09:03:00    3
2018-01-01 09:04:00    3
Name: num, dtype: int64

In [41]:
df.loc['2018'].groupby('city').sum()

              num
city
Cambridge  308428
Durham     307965
London     307431
Oxford     307366

### 10. Select data with a specific month or a specific day of the month

Al haber indizado un campo datetime me permite hacer las búsquedas desde el índice interpretado ya como una fecha

In [ ]:
#>Año y mes
df.loc['2018-5'].head()

                     num    city
date
2018-05-01 09:00:00    1  London
2018-05-01 09:01:00    4  London
2018-05-01 09:02:00    3  London
2018-05-01 09:03:00    2  London
2018-05-01 09:04:00    3  London

In [ ]:
#Día concreto
df.loc['2018-5-1'].head()

                     num    city
date
2018-05-01 09:00:00    1  London
2018-05-01 09:01:00    4  London
2018-05-01 09:02:00    3  London
2018-05-01 09:03:00    2  London
2018-05-01 09:04:00    3  London

In [ ]:
df.index.month

In [ ]:
cond = df.index.month == 2
df[cond].loc['2016']

### 11. Select data between two dates

In [44]:
df.sort_index().loc['2016':'2018']

                     num       city
date
2016-01-01 09:00:00    3  Cambridge
2016-01-01 09:00:00    4     London
2016-01-01 09:00:00    3     Durham
2016-01-01 09:00:00    3     Oxford
2016-01-01 09:01:00    2     Oxford
...                  ...        ...
2018-12-31 15:59:00    2     Oxford
2018-12-31 16:00:00    2     Durham
2018-12-31 16:00:00    3     Oxford
2018-12-31 16:00:00    2  Cambridge
2018-12-31 16:00:00    3     London

[1316888 rows x 2 columns]

In [ ]:
df.index

In [45]:
df.sort_index().loc['2018-5-2 10' : '2018-5-2 11']

                     num       city
date
2018-05-02 10:00:00    3  Cambridge
2018-05-02 10:00:00    3     Oxford
2018-05-02 10:00:00    3     Durham
2018-05-02 10:00:00    2     London
2018-05-02 10:01:00    3     London
...                  ...        ...
2018-05-02 11:58:00    4  Cambridge
2018-05-02 11:59:00    3     Durham
2018-05-02 11:59:00    1  Cambridge
2018-05-02 11:59:00    4     London
2018-05-02 11:59:00    3     Oxford

[480 rows x 2 columns]

In [46]:
df.sort_index().loc['2018-5-2 10:30' : '2018-5-2 10:45']

                     num       city
date
2018-05-02 10:30:00    3     London
2018-05-02 10:30:00    3     Oxford
2018-05-02 10:30:00    2     Durham
2018-05-02 10:30:00    3  Cambridge
2018-05-02 10:31:00    2     Durham
...                  ...        ...
2018-05-02 10:44:00    3  Cambridge
2018-05-02 10:45:00    4     London
2018-05-02 10:45:00    3     Durham
2018-05-02 10:45:00    3     Oxford
2018-05-02 10:45:00    1  Cambridge

[64 rows x 2 columns]

In [ ]:
df.between_time('10:30','10:45')

In [ ]:
df.shape

### 12. Operations with dates

In [48]:
df = pd.DataFrame({'name': ['Tom', 'Andy', 'Lucas'],
                 'DoB': ['08-05-1997', '04-28-1996', '12-16-1995']})

df['DoB'] = pd.to_datetime(df['DoB'])
df

    name        DoB
0    Tom 1997-08-05
1   Andy 1996-04-28
2  Lucas 1995-12-16

In [49]:
#Además del propio datetime hay más herramientas
from pandas.tseries.offsets import DateOffset, BDay

print(df['DoB'] + DateOffset(days = 5))
print(df['DoB'] + DateOffset(days = -5))
print(df['DoB'] + DateOffset(months = 5))

0   1997-08-10
1   1996-05-03
2   1995-12-21
Name: DoB, dtype: datetime64[us]
0   1997-07-31
1   1996-04-23
2   1995-12-11
Name: DoB, dtype: datetime64[us]
0   1998-01-05
1   1996-09-28
2   1996-05-16
Name: DoB, dtype: datetime64[us]

In [50]:
BDay(10)

In [ ]:
print(df['DoB'])
print(df['DoB'] + BDay(10))

In [ ]:
df['DoB+10BD'] = df['DoB'] + BDay(10) # Suma días laborables. Cuenta que no sean fin de semana (no llega a tema fiestas)
df

    name        DoB   DoB+10BD
0    Tom 1997-08-05 1997-08-19
1   Andy 1996-04-28 1996-05-10
2  Lucas 1995-12-16 1995-12-29

In [ ]:
#cuantos días normales me ha sumado
df['date_diff'] = (df['DoB+10BD'] - df['DoB']).dt.days
df

    name        DoB   DoB+10BD  date_diff
0    Tom 1997-08-05 1997-08-19         14
1   Andy 1996-04-28 1996-05-10         12
2  Lucas 1995-12-16 1995-12-29         13

In [ ]:
df.dtypes

### 13. Regular sequences: ``pd.date_range()``

To make the creation of **regular date** sequences more convenient, Pandas offers for this purpose ``pd.date_range()`` for timestamps.
We've seen that **Python's ``range()`` and NumPy's ``np.arange()``** turn a startpoint, endpoint, and optional stepsize into a sequence.
Similarly, ``pd.date_range()`` accepts a start date, an end date, and an optional frequency code to create a regular sequence of dates.
By default, the frequency is one day:

In [ ]:
#Crea rango de fechas entre dos: por defecto la crea en días
pd.date_range('2015-07-03', '2015-07-10')

DatetimeIndex(['2015-07-03', '2015-07-04', '2015-07-05', '2015-07-06',
               '2015-07-07', '2015-07-08', '2015-07-09', '2015-07-10'],
              dtype='datetime64[us]', freq='D')

Alternatively, the date range can be specified not with a start and endpoint, but with a startpoint and a number of periods:

In [ ]:
# Le puedo indicar cuantos periods (por defecto en días)
pd.date_range('2015-07-03', periods = 8)

DatetimeIndex(['2015-07-03', '2015-07-04', '2015-07-05', '2015-07-06',
               '2015-07-07', '2015-07-08', '2015-07-09', '2015-07-10'],
              dtype='datetime64[us]', freq='D')

The spacing can be modified by altering the ``freq`` argument, which defaults to ``D``.
For example, here we will construct a range of hourly timestamps:

In [ ]:
# ME - month end, me guarda el último día de cada mes
pd.date_range('2015-01-01', periods = 12, freq='ME')

DatetimeIndex(['2015-01-31', '2015-02-28', '2015-03-31', '2015-04-30',
               '2015-05-31', '2015-06-30', '2015-07-31', '2015-08-31',
               '2015-09-30', '2015-10-31', '2015-11-30', '2015-12-31'],
              dtype='datetime64[us]', freq='ME')

### 14. Handle missing values

In [56]:
# Creamos algunos missings de forma intencionada con la rolling window
df = pd.read_csv('data/city_sales.csv', parse_dates=['date'], index_col='date')
df

                     num       city
date
2015-01-01 09:00:00    4     London
2015-01-01 09:01:00    4     London
2015-01-01 09:02:00    3     London
2015-01-01 09:03:00    3     London
2015-01-01 09:04:00    3     London
...                  ...        ...
2019-01-31 15:56:00    3  Cambridge
2019-01-31 15:57:00    3  Cambridge
2019-01-31 15:58:00    3  Cambridge
2019-01-31 15:59:00    3  Cambridge
2019-01-31 16:00:00    2  Cambridge

[1795144 rows x 2 columns]

In [57]:
df['num']

date
2015-01-01 09:00:00    4
2015-01-01 09:01:00    4
2015-01-01 09:02:00    3
2015-01-01 09:03:00    3
2015-01-01 09:04:00    3
                      ..
2019-01-31 15:56:00    3
2019-01-31 15:57:00    3
2019-01-31 15:58:00    3
2019-01-31 15:59:00    3
2019-01-31 16:00:00    2
Name: num, Length: 1795144, dtype: int64

In [ ]:
# La idea central es que .rolling(3) crea una "ventana" de 3 filas que se va desplazando hacia abajo una a una. En cada posición, 
# .sum() suma los 3 valores que caen dentro de esa ventana y escribe el resultado en rolling_sum.
# Las dos primeras filas (índice 0 y 1) siempre salen como NaN porque todavía no hay 3 valores disponibles para completar 
# la ventana. A partir de la fila 2 ya hay suficientes y el cálculo empieza a funcionar.

df['rolling_sum'] = df['num'].rolling(3).sum()
df.head()

                     num    city  rolling_sum
date
2015-01-01 09:00:00    4  London          NaN
2015-01-01 09:01:00    4  London          NaN
2015-01-01 09:02:00    3  London         11.0
2015-01-01 09:03:00    3  London         10.0
2015-01-01 09:04:00    3  London          9.0

In [ ]:
# .bfill(): Significa "Backward Fill" (relleno hacia atrás). Busca el siguiente valor válido (que no sea NaN)
# y lo copia hacia arriba para rellenar los huecos anteriores.
df['rolling_sum_back'] = df['rolling_sum'].bfill()
df.head()

In [59]:
# Creating the dataframe 
df = pd.DataFrame({"A":[12, 4, 5, None, 1],
                   "B":[None, 2, 54, 3, None],
                   "C":[20, 16, None, 3, 8],
                   "D":[14, 3, None, None, 12]})
  
# Print the dataframe
df

      A     B     C     D
0  12.0   NaN  20.0  14.0
1   4.0   2.0  16.0   3.0
2   5.0  54.0   NaN   NaN
3   NaN   3.0   3.0   NaN
4   1.0   NaN   8.0  12.0

In [60]:
df.interpolate(method = 'linear')

      A     B     C     D
0  12.0   NaN  20.0  14.0
1   4.0   2.0  16.0   3.0
2   5.0  54.0   9.5   6.0
3   3.0   3.0   3.0   9.0
4   1.0   3.0   8.0  12.0